---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - ec2_vpc_net_info
    - ec2_security_group_info
    - ec2_vpc_subnet_info
    - route53_resolver_info

  post_tasks:
    - name: Ensure role is included without name
      ansible.builtin.include_role:
        name: route53_resolver_rule_info
      vars:
        route53_resolver_rule_info_filters: {}

    - name: Ensure info without name is verified
      ansible.builtin.assert:
        that:
          - _route53_resolver_rule_info_dict['molecule-cloudflare'].arn is defined
          - _route53_resolver_rule_info_dict['molecule-cloudflare'].domain_name ==
              route53_resolver_rule_list.0.domain_name ~ '.'
          - _route53_resolver_rule_info_dict['molecule-cloudflare'].id is defined
          - _route53_resolver_rule_info_dict['molecule-cloudflare'].resolver_endpoint_id ==
              route53_resolver_rule_list.0.resolver_endpoint_id
          - _route53_resolver_rule_info_dict['molecule-cloudflare'].rule_type ==
              route53_resolver_rule_list.0.rule_type | upper
          - _route53_resolver_rule_info_dict['molecule-cloudflare'].status == 'COMPLETE'
          - _route53_resolver_rule_info_dict['molecule-cloudflare'].target_ips |
            json_query('[].[ip, port]') |
            sort ==
              route53_resolver_rule_list.0.target_ips |
              json_query('[].[ip, port]') |
              sort
          - _route53_resolver_rule_info_dict['molecule-cloudflare'].associations | length == 1
          - _route53_resolver_rule_info_dict['molecule-cloudflare'].associations.0.name ==
              route53_resolver_rule_associate_list.0.name
          - _route53_resolver_rule_info_dict['molecule-cloudflare'].associations.0.vpc_id ==
              route53_resolver_rule_associate_list.0.vpc_id
          - _route53_resolver_rule_info_dict['molecule-cloudflare'].vpc_ids ==
              [route53_resolver_rule_associate_list.0.vpc_id]
          - _route53_resolver_rule_info_dict['molecule-google'].arn is defined
          - _route53_resolver_rule_info_dict['molecule-google'].domain_name ==
              route53_resolver_rule_list.1.domain_name ~ '.'
          - _route53_resolver_rule_info_dict['molecule-google'].id is defined
          - _route53_resolver_rule_info_dict['molecule-google'].resolver_endpoint_id ==
              route53_resolver_rule_list.1.resolver_endpoint_id
          - _route53_resolver_rule_info_dict['molecule-google'].rule_type ==
              route53_resolver_rule_list.1.rule_type | upper
          - _route53_resolver_rule_info_dict['molecule-google'].status == 'COMPLETE'
          - _route53_resolver_rule_info_dict['molecule-google'].target_ips |
            json_query('[].[ip, port]') |
            sort ==
              route53_resolver_rule_list.1.target_ips |
              json_query('[].[ip, port]') |
              sort
          - _route53_resolver_rule_info_dict['molecule-google'].associations | length == 1
          - _route53_resolver_rule_info_dict['molecule-google'].associations.0.name ==
              route53_resolver_rule_associate_list.1.name
          - _route53_resolver_rule_info_dict['molecule-google'].associations.0.vpc_id ==
              route53_resolver_rule_associate_list.1.vpc_id
          - _route53_resolver_rule_info_dict['molecule-google'].vpc_ids ==
              [route53_resolver_rule_associate_list.1.vpc_id]

    - name: Ensure role is included with name
      ansible.builtin.include_role:
        name: route53_resolver_rule_info
      vars:
        route53_resolver_rule_info_filters:
          Name: "{{ route53_resolver_rule_list.0.name }}"

    - name: Ensure info with name is verified
      ansible.builtin.assert:
        that:
          - _route53_resolver_rule_info_list | length == 1
          - _route53_resolver_rule_info_list.0.name == route53_resolver_rule_list.0.name
          - _route53_resolver_rule_info_dict.keys() | list == [route53_resolver_rule_list.0.name]
          - _route53_resolver_rule_info_dict[route53_resolver_rule_list.0.name].arn is defined
          - _route53_resolver_rule_info_dict[route53_resolver_rule_list.0.name].domain_name ==
              route53_resolver_rule_list.0.domain_name ~ '.'
          - _route53_resolver_rule_info_dict[route53_resolver_rule_list.0.name].resolver_endpoint_id ==
              route53_resolver_rule_list.0.resolver_endpoint_id
          - _route53_resolver_rule_info_dict[route53_resolver_rule_list.0.name].rule_type ==
              route53_resolver_rule_list.0.rule_type | upper
          - _route53_resolver_rule_info_dict[route53_resolver_rule_list.0.name].vpc_ids ==
              [route53_resolver_rule_associate_list.0.vpc_id]

    - name: Ensure role is included without name
      ansible.builtin.include_role:
        name: route53_resolver_rule_info
      vars:
        route53_resolver_rule_info_filters: {}

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        ec2_security_group_list:
          - vpc_id: "{{ _ec2_vpc_net_info_dict['molecule'].id }}"
            security_groups:
              "{{ ec2_security_group_list.0.security_groups |
                  map('combine', {'state': 'absent'}) }}"
        ec2_vpc_net_list:
          "{{ ec2_vpc_net_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_vpc_subnet_list:
          "{{ ec2_vpc_subnet_list |
              map('combine', {'state': 'absent'}) }}"
        route53_resolver_list:
          "{{ route53_resolver_list |
              map('combine', {'state': 'absent'}) }}"
        route53_resolver_rule_list:
          "{{ route53_resolver_rule_list |
              map('combine', {'state': 'absent'}) }}"
        route53_resolver_rule_associate_list:
          "{{ route53_resolver_rule_associate_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _verify }}"
      loop:
        - route53_resolver_rule_associate
        - route53_resolver_rule
        - route53_resolver
        - ec2_security_group
        - ec2_vpc_subnet
        - ec2_vpc_net
      loop_control:
        label: "{{ _verify }}"
        loop_var: _verify
...
