---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  tasks:
    - name: Ensure role is included
      ansible.builtin.include_role:
        name: pinpoint_sms_voice_phone_number_info

    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _pinpoint_sms_voice_phone_number_info_list.0.iso_country_code == 'US'
          - _pinpoint_sms_voice_phone_number_info_list.0.message_type == 'TRANSACTIONAL'
          - _pinpoint_sms_voice_phone_number_info_list.0.number_capabilities.0 == 'SMS'
          - _pinpoint_sms_voice_phone_number_info_list.0.number_type == 'SIMULATOR'
          - _pinpoint_sms_voice_phone_number_info_list.0.phone_number is defined
          - _pinpoint_sms_voice_phone_number_info_list.0.phone_number_arn is defined
          - _pinpoint_sms_voice_phone_number_info_list.0.phone_number_id is defined
          - _pinpoint_sms_voice_phone_number_info_list.0.status == 'ACTIVE'

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        pinpoint_sms_voice_phone_number_list:
          "{{ pinpoint_sms_voice_phone_number_list |
              map('combine',
                  {'phone_number_id':
                   _pinpoint_sms_voice_phone_number_info_list.0.phone_number_id,
                   'state':
                   'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _verify }}"
      loop:
        - pinpoint_sms_voice_phone_number
      loop_control:
        label: "{{ _verify }}"
        loop_var: _verify
...
