---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9.6
    cpus: 4
    memory: 4096

provisioner:
  name: ansible
  env:
    ANSIBLE_ACTION_WARNINGS: false
    ANSIBLE_DEPRECATION_WARNINGS: false
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /opt/awscli/bin/python
        sns_topic_list:
          - name: molecule-bounce
            display_name: molecule-bounce
            subscriptions:
              - endpoint: "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-bounce"
                protocol: sqs
            policy:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    Service: ses.amazonaws.com
                  Action:
                    - sns:Publish
                  Resource:
                    - "arn:aws:sns:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-bounce"
                  Condition:
                    StringEquals:
                      'AWS:SourceAccount': "{{ _aws_caller_info_account }}"
                      'AWS:SourceArn':
                        - "arn:aws:ses:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:identity/molecule.org"

          - name: molecule-complaint
            display_name: molecule-complaint
            subscriptions:
              - endpoint: "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-complaint"
                protocol: sqs
            policy:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    Service: ses.amazonaws.com
                  Action:
                    - sns:Publish
                  Resource:
                    - "arn:aws:sns:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-complaint"
                  Condition:
                    StringEquals:
                      'AWS:SourceAccount': "{{ _aws_caller_info_account }}"
                      'AWS:SourceArn':
                        - "arn:aws:ses:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:identity/molecule.org"

          - name: molecule-delivery
            display_name: molecule-delivery
            subscriptions:
              - endpoint: "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-delivery"
                protocol: sqs
            policy:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    Service: ses.amazonaws.com
                  Action:
                    - sns:Publish
                  Resource:
                    - "arn:aws:sns:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-delivery"
                  Condition:
                    StringEquals:
                      'AWS:SourceAccount': "{{ _aws_caller_info_account }}"
                      'AWS:SourceArn':
                        - "arn:aws:ses:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:identity/molecule.org"

        sqs_queue_list:
          - name: molecule-bounce
            policy:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    AWS:
                      - "arn:aws:iam::{{ _aws_caller_info_account }}:root"
                  Action:
                    - sqs:*
                  Resource:
                    - "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-bounce"
                - Effect: Allow
                  Principal:
                    Service: sns.amazonaws.com
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-bounce"
                  Condition:
                    ArnEquals:
                      'aws:SourceArn':
                        "arn:aws:sns:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-bounce"

          - name: molecule-complaint
            policy:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    AWS:
                      - "arn:aws:iam::{{ _aws_caller_info_account }}:root"
                  Action:
                    - sqs:*
                  Resource:
                    - "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-complaint"
                - Effect: Allow
                  Principal:
                    Service: sns.amazonaws.com
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-complaint"
                  Condition:
                    ArnEquals:
                      'aws:SourceArn':
                        "arn:aws:sns:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-complaint"

          - name: molecule-delivery
            policy:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    AWS:
                      - "arn:aws:iam::{{ _aws_caller_info_account }}:root"
                  Action:
                    - sqs:*
                  Resource:
                    - "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-delivery"
                - Effect: Allow
                  Principal:
                    Service: sns.amazonaws.com
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-delivery"
                  Condition:
                    ArnEquals:
                      'aws:SourceArn':
                        "arn:aws:sns:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-delivery"

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
