---
- name: Ensure aws route53 resolver endpoints are managed
  tags:
    - route53_resolver
  linuxhq.aws.route53_resolver:
    direction: "{{ _route53resolver.direction }}"
    ip_addresses: "{{ _route53resolver.ip_addresses }}"
    name: "{{ _route53resolver.name }}"
    purge_tags: "{{ _route53resolver.purge_tags | d(true) }}"
    protocols: "{{ _route53resolver.protocols | d(['do53']) }}"
    resolver_endpoint_type: "{{ _route53resolver.resolver_endpoint_type | d('ipv4') }}"
    security_group_ids: "{{ _route53resolver.security_group_ids }}"
    state: "{{ _route53resolver.state | d('present') }}"
    tags: "{{ _route53resolver.tags | d({}) | combine({'Name': _route53resolver.name}) }}"
    validate_certs: true
    wait: "{{ _route53resolver.wait | d(true) }}"
    wait_delay: 5
    wait_timeout: "{{ _route53resolver.wait_timeout | d(route53_resolver_timeout) }}"
  register: __route53_resolver_result
  loop: "{{ __route53_resolver_list }}"
  loop_control:
    label: "{{ _route53resolver.name | d(none) }}"
    loop_var: _route53resolver
  async: "{{ ansible_check_mode | ternary(0, route53_resolver_async) }}"
  poll: "{{ route53_resolver_poll }}"
  when:
    - _route53resolver.name is defined
    - _route53resolver.direction is defined
    - _route53resolver.ip_addresses is defined
    - _route53resolver.ip_addresses | length > 0
    - _route53resolver.security_group_ids is defined
    - _route53resolver.security_group_ids | length > 0
  changed_when:
    - ansible_check_mode | bool
    - __route53_resolver_result.changed | bool

- name: Ensure managed aws route53 resolver endpoint jobs are complete
  tags:
    - route53_resolver
  ansible.builtin.async_status:
    jid: "{{ _jid.ansible_job_id }}"
  register: __route53_resolver_status
  loop: "{{ __route53_resolver_result.results }}"
  loop_control:
    label: "{{ _jid._route53resolver.name | d(none) }}"
    loop_var: _jid
  delay: "{{ route53_resolver_delay }}"
  retries: "{{ route53_resolver_retries }}"
  when:
    - _jid.ansible_job_id is defined
  until:
    - __route53_resolver_status.finished | bool
...
