---
- name: Ensure aws route53 resolver endpoints are batched
  tags:
    - route53_resolver
  ansible.builtin.include_tasks:
    apply:
      tags:
        - route53_resolver
    file: include.yml
  loop:
    "{{ route53_resolver_list |
        batch(route53_resolver_batch) }}"
  loop_control:
    label: "{{ __route53_resolver_list | length }}"
    loop_var: __route53_resolver_list
...
