---
- name: Ensure aws route53 resolver rule associations are managed
  tags:
    - route53_resolver_rule_associate
  linuxhq.aws.route53_resolver_rule_associate:
    name: "{{ _resolver_rule_association.name }}"
    resolver_rule_id: "{{ _resolver_rule_association.resolver_rule_id }}"
    state: "{{ _resolver_rule_association.state | d('present') }}"
    validate_certs: true
    vpc_id: "{{ _resolver_rule_association.vpc_id }}"
    wait: "{{ _resolver_rule_association.wait | d(true) }}"
    wait_delay: 5
    wait_timeout: 300
  register: __route53_resolver_rule_associate_result
  loop: "{{ __route53_resolver_rule_associate_list }}"
  loop_control:
    label: "{{ _resolver_rule_association.name | d(none) }}"
    loop_var: _resolver_rule_association
  async: "{{ ansible_check_mode | ternary(0, route53_resolver_rule_associate_async) }}"
  poll: "{{ route53_resolver_rule_associate_poll }}"
  when:
    - _resolver_rule_association.name is defined
    - _resolver_rule_association.resolver_rule_id is defined
    - _resolver_rule_association.vpc_id is defined
  changed_when:
    - ansible_check_mode | bool
    - __route53_resolver_rule_associate_result.changed | bool

- name: Ensure managed aws route53 resolver rule association jobs are complete
  tags:
    - route53_resolver_rule_associate
  ansible.builtin.async_status:
    jid: "{{ _jid.ansible_job_id }}"
  register: __route53_resolver_rule_associate_status
  loop: "{{ __route53_resolver_rule_associate_result.results }}"
  loop_control:
    label: "{{ _jid._resolver_rule_association.name | d(none) }}"
    loop_var: _jid
  delay: "{{ route53_resolver_rule_associate_delay }}"
  retries: "{{ route53_resolver_rule_associate_retries }}"
  when:
    - _jid.ansible_job_id is defined
  until:
    - __route53_resolver_rule_associate_status.finished | bool
...
