---
- name: Ensure aws route53 resolver rule associations are batched
  tags:
    - route53_resolver_rule_associate
  ansible.builtin.include_tasks:
    apply:
      tags:
        - route53_resolver_rule_associate
    file: include.yml
  loop:
    "{{ route53_resolver_rule_associate_list |
        batch(route53_resolver_rule_associate_batch) }}"
  loop_control:
    label: "{{ __route53_resolver_rule_associate_list | length }}"
    loop_var: __route53_resolver_rule_associate_list
...
