---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: aws_caller_info
      check_mode: false

    - role: iam_role
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: kms_key
      kms_key_list: []
      tags:
        - molecule-idempotence-notest

    - kms_key
...
