---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - aws_caller_info

  post_tasks:
    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        iam_role_list:
          "{{ iam_role_list |
              map('combine', {'state': 'absent'}) }}"
        kms_key_list:
          "{{ kms_key_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _verify }}"
      loop:
        - kms_key
        - iam_role
      loop_control:
        label: "{{ _verify }}"
        loop_var: _verify
...
