---
- name: Ensure aws elastic load balancer application load balancer is absent
  tags:
    - elb_application_lb
  amazon.aws.elb_application_lb:
    name: "{{ _loadbalancer.name }}"
    state: "{{ _loadbalancer.state }}"
    validate_certs: true

- name: Ensure aws elastic load balancer application load balancer security group is absent
  tags:
    - elb_application_lb
  amazon.aws.ec2_security_group:
    name: "{{ _loadbalancer.name }}"
    state: "{{ _loadbalancer.state }}"
    validate_certs: true
  register: __elb_application_lb_security_group_result
  until:
    - __elb_application_lb_security_group_result is success
  delay: 5
  retries: 60
...
