---
- name: Ensure aws application load balancers are batched
  tags:
    - elb_application_lb
  ansible.builtin.include_tasks:
    apply:
      tags:
        - elb_application_lb
    file: include.yml
  loop:
    "{{ elb_application_lb_list |
        batch(elb_application_lb_batch) }}"
  loop_control:
    label: "{{ __elb_application_lb_list | length }}"
    loop_var: __elb_application_lb_list
...
