---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: ec2_customer_gateway
      ec2_customer_gateway_list: []
      tags:
        - molecule-idempotence-notest

    - ec2_customer_gateway
...
