---
- name: Ensure aws simple storage service buckets are batched
  tags:
    - s3_bucket
  ansible.builtin.include_tasks:
    apply:
      tags:
        - s3_bucket
    file: include.yml
  loop:
    "{{ s3_bucket_list |
        batch(s3_bucket_batch) }}"
  loop_control:
    label: "{{ __s3_bucket_list | length }}"
    loop_var: __s3_bucket_list
...
