---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  pre_tasks:
    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        iam_oidc_provider_list:
          "{{ iam_oidc_provider_idempotence |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - iam_oidc_provider
...
