---
- name: Ensure aws end user messaging sms phone pools are batched
  tags:
    - pinpoint_sms_voice_phone_pool
  ansible.builtin.include_tasks:
    apply:
      tags:
        - pinpoint_sms_voice_phone_pool
    file: include.yml
  loop:
    "{{ pinpoint_sms_voice_phone_pool_list |
        batch(pinpoint_sms_voice_phone_pool_batch) }}"
  loop_control:
    label: "{{ __pinpoint_sms_voice_phone_pool_list | length }}"
    loop_var: __pinpoint_sms_voice_phone_pool_list
...
