---
- name: Ensure information about aws route53 resolver endpoints is gathered
  tags:
    - route53_resolver_info
  linuxhq.aws.route53_resolver_info:
    filters: "{{ route53_resolver_info_filters }}"
    validate_certs: true
  register: __route53_resolver_info_query

- name: Ensure list of aws route53 resolver endpoints is generated
  tags:
    - route53_resolver_info
  ansible.builtin.set_fact:
    _route53_resolver_info_list:
      "{{ __route53_resolver_info_query.resolver_endpoints |
          d([]) }}"

- name: Ensure dict of aws route53 resolver endpoints is generated
  tags:
    - route53_resolver_info
  ansible.builtin.set_fact:
    _route53_resolver_info_dict:
      "{{ dict(_route53_resolver_info_list |
               json_query('[].name') |
               zip(_route53_resolver_info_list)) }}"
...
