---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: s3_bucket
      s3_bucket_list: []
      tags:
        - molecule-idempotence-notest

    - s3_bucket
...
