---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  pre_tasks:
    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        s3_bucket_list:
          "{{ s3_bucket_list |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - s3_bucket
...
