---
- name: Ensure information about aws transit gateway vpc attachments is gathered
  tags:
    - ec2_transit_gateway_vpc_attachment_info
  amazon.aws.ec2_transit_gateway_vpc_attachment_info:
    filters: "{{ ec2_transit_gateway_vpc_attachment_info_filters or omit }}"
    id: "{{ ec2_transit_gateway_vpc_attachment_info_id or omit }}"
    include_deleted: "{{ ec2_transit_gateway_vpc_attachment_info_include_deleted }}"
    name: "{{ ec2_transit_gateway_vpc_attachment_info_name or omit }}"
    validate_certs: true
  register: __ec2_transit_gateway_vpc_attachment_info_query

- name: Ensure list of aws transit gateway vpc attachments is generated
  tags:
    - ec2_transit_gateway_vpc_attachment_info
  ansible.builtin.set_fact:
    _ec2_transit_gateway_vpc_attachment_info_list:
      "{{ (__ec2_transit_gateway_vpc_attachment_info_query.attachments |
          selectattr('tags.Name', 'defined')) |
          d([]) }}"

- name: Ensure dict of aws transit gateway vpc attachments is generated
  tags:
    - ec2_transit_gateway_vpc_attachment_info
  ansible.builtin.set_fact:
    _ec2_transit_gateway_vpc_attachment_info_dict:
      "{{ dict(_ec2_transit_gateway_vpc_attachment_info_list |
               json_query('[].tags.Name') |
               zip(_ec2_transit_gateway_vpc_attachment_info_list)) }}"
...
