---
- name: Ensure aws iam account alias is managed
  tags:
    - iam_account_alias
  linuxhq.aws.iam_account_alias:
    name: "{{ iam_account_alias_name }}"
    state: "{{ iam_account_alias_state }}"
    validate_certs: true
  when:
    - iam_account_alias_name is not none
...
