---
- name: Ensure aws systems manager parameter tasks are batched
  tags:
    - ssm_parameter
  ansible.builtin.include_tasks:
    apply:
      tags:
        - ssm_parameter
    file: include.yml
  loop:
    "{{ ssm_parameter_list |
        batch(ssm_parameter_batch) }}"
  loop_control:
    label: "{{ __ssm_parameter_list | length }}"
    loop_var: __ssm_parameter_list
...
