---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: notifications_hub
      notifications_hub_list: []
      tags:
        - molecule-idempotence-notest

    - notifications_hub
...
