---
glue_connection_info_apply_override_for_compute_environment: null
glue_connection_info_catalog_id: null
glue_connection_info_filters: {}
glue_connection_info_hide_password: true
glue_connection_info_name: null
...
