---
- name: Ensure information about aws virtual private cloud endpoints is gathered
  tags:
    - ec2_vpc_endpoint_info
  amazon.aws.ec2_vpc_endpoint_info:
    filters: "{{ ec2_vpc_endpoint_info_filters }}"
    validate_certs: true
    vpc_endpoint_ids: "{{ ec2_vpc_endpoint_info_vpc_endpoint_ids }}"
  register: __ec2_vpc_endpoint_info_query

- name: Ensure list of aws virtual private cloud endpoints is generated
  tags:
    - ec2_vpc_endpoint_info
  ansible.builtin.set_fact:
    _ec2_vpc_endpoint_info_list:
      "{{ __ec2_vpc_endpoint_info_query.vpc_endpoints | d([]) |
          zip(__ec2_vpc_endpoint_info_query.vpc_endpoints | d([]) |
              map(attribute='tags') |
              map('default', []) |
              map('json_query', '[].{key: key || Key, value: value || Value}') |
              map('items2dict') |
              map('community.general.dict_kv', 'tags')) |
          map('combine') |
          list }}"

- name: Ensure dict of aws virtual private cloud endpoints is generated
  tags:
    - ec2_vpc_endpoint_info
  ansible.builtin.set_fact:
    _ec2_vpc_endpoint_info_dict:
      "{{ dict(_ec2_vpc_endpoint_info_list |
               json_query('[].tags.Name') |
               zip(_ec2_vpc_endpoint_info_list)) }}"
...
