---
- name: Ensure information about aws notifications hubs is gathered
  tags:
    - notifications_hub_info
  linuxhq.aws.notifications_hub_info:
    validate_certs: true
  register: __notifications_hub_info_query

- name: Ensure list of aws notifications hubs is generated
  tags:
    - notifications_hub_info
  ansible.builtin.set_fact:
    _notifications_hub_info_list:
      "{{ __notifications_hub_info_query.notification_hubs |
          d([]) |
          selectattr('notification_hub_region', 'defined') }}"

- name: Ensure dict of aws notifications hubs is generated
  tags:
    - notifications_hub_info
  ansible.builtin.set_fact:
    _notifications_hub_info_dict:
      "{{ dict(_notifications_hub_info_list |
               json_query('[].notification_hub_region') |
               zip(_notifications_hub_info_list)) }}"
...
