---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: ecs_ecr
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ecs_ecr_info
      ecs_ecr_info_name: molecule-00
...
