---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - ecs_ecr_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _ecs_ecr_info_dict['molecule-00'].encryption_configuration.encryption_type == 'AES256'
          - _ecs_ecr_info_dict['molecule-00'].image_scanning_configuration.scan_on_push | bool
          - _ecs_ecr_info_dict['molecule-00'].image_tag_mutability == 'IMMUTABLE'
          - _ecs_ecr_info_dict['molecule-00'].registry_id is defined
          - _ecs_ecr_info_dict['molecule-00'].repository_arn is defined
          - _ecs_ecr_info_dict['molecule-00'].repository_name is defined
          - _ecs_ecr_info_dict['molecule-00'].repository_uri is defined
          - _ecs_ecr_info_dict['molecule-01'].encryption_configuration.encryption_type == 'AES256'
          - _ecs_ecr_info_dict['molecule-01'].image_scanning_configuration.scan_on_push | bool
          - _ecs_ecr_info_dict['molecule-01'].image_tag_mutability == 'IMMUTABLE'
          - _ecs_ecr_info_dict['molecule-01'].registry_id is defined
          - _ecs_ecr_info_dict['molecule-01'].repository_arn is defined
          - _ecs_ecr_info_dict['molecule-01'].repository_name is defined
          - _ecs_ecr_info_dict['molecule-01'].repository_uri is defined
          - _ecs_ecr_info_dict['molecule-02'].encryption_configuration.encryption_type == 'AES256'
          - _ecs_ecr_info_dict['molecule-02'].image_scanning_configuration.scan_on_push | bool
          - _ecs_ecr_info_dict['molecule-02'].image_tag_mutability == 'IMMUTABLE'
          - _ecs_ecr_info_dict['molecule-02'].registry_id is defined
          - _ecs_ecr_info_dict['molecule-02'].repository_arn is defined
          - _ecs_ecr_info_dict['molecule-02'].repository_name is defined
          - _ecs_ecr_info_dict['molecule-02'].repository_uri is defined
          - _ecs_ecr_info_dict['molecule-03'].encryption_configuration.encryption_type == 'AES256'
          - _ecs_ecr_info_dict['molecule-03'].image_scanning_configuration.scan_on_push | bool
          - _ecs_ecr_info_dict['molecule-03'].image_tag_mutability == 'IMMUTABLE'
          - _ecs_ecr_info_dict['molecule-03'].registry_id is defined
          - _ecs_ecr_info_dict['molecule-03'].repository_arn is defined
          - _ecs_ecr_info_dict['molecule-03'].repository_name is defined
          - _ecs_ecr_info_dict['molecule-03'].repository_uri is defined
          - _ecs_ecr_info_dict['molecule-04'].encryption_configuration.encryption_type == 'AES256'
          - _ecs_ecr_info_dict['molecule-04'].image_scanning_configuration.scan_on_push | bool
          - _ecs_ecr_info_dict['molecule-04'].image_tag_mutability == 'IMMUTABLE'
          - _ecs_ecr_info_dict['molecule-04'].registry_id is defined
          - _ecs_ecr_info_dict['molecule-04'].repository_arn is defined
          - _ecs_ecr_info_dict['molecule-04'].repository_name is defined
          - _ecs_ecr_info_dict['molecule-04'].repository_uri is defined
          - _ecs_ecr_info_dict['molecule-05'].encryption_configuration.encryption_type == 'AES256'
          - _ecs_ecr_info_dict['molecule-05'].image_scanning_configuration.scan_on_push | bool
          - _ecs_ecr_info_dict['molecule-05'].image_tag_mutability == 'IMMUTABLE'
          - _ecs_ecr_info_dict['molecule-05'].registry_id is defined
          - _ecs_ecr_info_dict['molecule-05'].repository_arn is defined
          - _ecs_ecr_info_dict['molecule-05'].repository_name is defined
          - _ecs_ecr_info_dict['molecule-05'].repository_uri is defined
          - _ecs_ecr_info_dict['molecule-06'].encryption_configuration.encryption_type == 'AES256'
          - _ecs_ecr_info_dict['molecule-06'].image_scanning_configuration.scan_on_push | bool
          - _ecs_ecr_info_dict['molecule-06'].image_tag_mutability == 'IMMUTABLE'
          - _ecs_ecr_info_dict['molecule-06'].registry_id is defined
          - _ecs_ecr_info_dict['molecule-06'].repository_arn is defined
          - _ecs_ecr_info_dict['molecule-06'].repository_name is defined
          - _ecs_ecr_info_dict['molecule-06'].repository_uri is defined
          - _ecs_ecr_info_dict['molecule-07'].encryption_configuration.encryption_type == 'AES256'
          - _ecs_ecr_info_dict['molecule-07'].image_scanning_configuration.scan_on_push | bool
          - _ecs_ecr_info_dict['molecule-07'].image_tag_mutability == 'IMMUTABLE'
          - _ecs_ecr_info_dict['molecule-07'].registry_id is defined
          - _ecs_ecr_info_dict['molecule-07'].repository_arn is defined
          - _ecs_ecr_info_dict['molecule-07'].repository_name is defined
          - _ecs_ecr_info_dict['molecule-07'].repository_uri is defined
          - _ecs_ecr_info_dict['molecule-08'].encryption_configuration.encryption_type == 'AES256'
          - _ecs_ecr_info_dict['molecule-08'].image_scanning_configuration.scan_on_push | bool
          - _ecs_ecr_info_dict['molecule-08'].image_tag_mutability == 'IMMUTABLE'
          - _ecs_ecr_info_dict['molecule-08'].registry_id is defined
          - _ecs_ecr_info_dict['molecule-08'].repository_arn is defined
          - _ecs_ecr_info_dict['molecule-08'].repository_name is defined
          - _ecs_ecr_info_dict['molecule-08'].repository_uri is defined
          - _ecs_ecr_info_dict['molecule-09'].encryption_configuration.encryption_type == 'AES256'
          - _ecs_ecr_info_dict['molecule-09'].image_scanning_configuration.scan_on_push | bool
          - _ecs_ecr_info_dict['molecule-09'].image_tag_mutability == 'IMMUTABLE'
          - _ecs_ecr_info_dict['molecule-09'].registry_id is defined
          - _ecs_ecr_info_dict['molecule-09'].repository_arn is defined
          - _ecs_ecr_info_dict['molecule-09'].repository_name is defined
          - _ecs_ecr_info_dict['molecule-09'].repository_uri is defined
          - _ecs_ecr_info_dict['molecule-10'].encryption_configuration.encryption_type == 'AES256'
          - _ecs_ecr_info_dict['molecule-10'].image_scanning_configuration.scan_on_push | bool
          - _ecs_ecr_info_dict['molecule-10'].image_tag_mutability == 'IMMUTABLE'
          - _ecs_ecr_info_dict['molecule-10'].registry_id is defined
          - _ecs_ecr_info_dict['molecule-10'].repository_arn is defined
          - _ecs_ecr_info_dict['molecule-10'].repository_name is defined
          - _ecs_ecr_info_dict['molecule-10'].repository_uri is defined
          - _ecs_ecr_info_dict['molecule-11'].encryption_configuration.encryption_type == 'AES256'
          - _ecs_ecr_info_dict['molecule-11'].image_scanning_configuration.scan_on_push | bool
          - _ecs_ecr_info_dict['molecule-11'].image_tag_mutability == 'IMMUTABLE'
          - _ecs_ecr_info_dict['molecule-11'].registry_id is defined
          - _ecs_ecr_info_dict['molecule-11'].repository_arn is defined
          - _ecs_ecr_info_dict['molecule-11'].repository_name is defined
          - _ecs_ecr_info_dict['molecule-11'].repository_uri is defined

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        ecs_ecr_list:
          "{{ ecs_ecr_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _verify }}"
      loop:
        - ecs_ecr
      loop_control:
        label: "{{ _verify }}"
        loop_var: _verify
...
