---
- name: Ensure information about aws systems manager documents is gathered
  tags:
    - ssm_document_info
  linuxhq.aws.ssm_document_info:
    document_format: "{{ ssm_document_info_document_format }}"
    document_version: "{{ ssm_document_info_document_version or omit }}"
    filters: "{{ ssm_document_info_filters }}"
    names: "{{ ssm_document_info_names or omit }}"
    validate_certs: true
    version_name: "{{ ssm_document_info_version_name or omit }}"
  register: __ssm_document_info_query

- name: Ensure list of aws systems manager documents is generated
  tags:
    - ssm_document_info
  ansible.builtin.set_fact:
    _ssm_document_info_list:
      "{{ __ssm_document_info_query.documents |
          d([]) }}"

- name: Ensure dict of aws systems manager documents is generated
  tags:
    - ssm_document_info
  ansible.builtin.set_fact:
    _ssm_document_info_dict:
      "{{ dict(_ssm_document_info_list |
               json_query('[].name') |
               zip(_ssm_document_info_list)) }}"
...
