---
- name: Ensure aws simple storage service bucket websites are batched
  tags:
    - s3_website
  ansible.builtin.include_tasks:
    apply:
      tags:
        - s3_website
    file: include.yml
  loop:
    "{{ s3_website_list |
        batch(s3_website_batch) }}"
  loop_control:
    label: "{{ __s3_website_list | length }}"
    loop_var: __s3_website_list
...
