---
- name: Ensure information about aws glue connections is gathered
  tags:
    - glue_connection_info
  ansible.builtin.command:
    cmd: >
      aws glue get-connections
        --query ConnectionList
  register: __glue_connection_info_query
  check_mode: false
  changed_when: false

- name: Ensure list of aws glue connections is generated
  tags:
    - glue_connection_info
  ansible.builtin.set_fact:
    _glue_connection_info_list:
      "{{ (__glue_connection_info_query.stdout |
          from_json) |
          d([]) }}"

- name: Ensure dict of aws glue connections is generated
  tags:
    - glue_connection_info
  ansible.builtin.set_fact:
    _glue_connection_info_dict:
      "{{ dict(_glue_connection_info_list |
               json_query('[].Name') |
               zip(_glue_connection_info_list)) }}"
...
