---
- name: Ensure information about aws glue connections is gathered
  tags:
    - glue_connection_info
  linuxhq.aws.glue_connection_info:
    apply_override_for_compute_environment:
      "{{ glue_connection_info_apply_override_for_compute_environment }}"
    catalog_id: "{{ glue_connection_info_catalog_id or omit }}"
    filters: "{{ glue_connection_info_filters }}"
    hide_password: "{{ glue_connection_info_hide_password }}"
    names: "{{ glue_connection_info_names or omit }}"
    validate_certs: true
  register: __glue_connection_info_query

- name: Ensure list of aws glue connections is generated
  tags:
    - glue_connection_info
  ansible.builtin.set_fact:
    _glue_connection_info_list:
      "{{ __glue_connection_info_query.connections |
          d([]) }}"

- name: Ensure dict of aws glue connections is generated
  tags:
    - glue_connection_info
  ansible.builtin.set_fact:
    _glue_connection_info_dict:
      "{{ dict(_glue_connection_info_list |
               json_query('[].name') |
               zip(_glue_connection_info_list)) }}"
...
