---
- name: Ensure information about aws end user messaging sms phone pools is gathered
  tags:
    - pinpoint_sms_voice_phone_pool_info
  linuxhq.aws.pinpoint_sms_voice_phone_pool_info:
    filters: "{{ pinpoint_sms_voice_phone_pool_info_filters }}"
    max_results: "{{ pinpoint_sms_voice_phone_pool_info_max_results or omit }}"
    owner: "{{ pinpoint_sms_voice_phone_pool_info_owner }}"
    pool_ids: "{{ pinpoint_sms_voice_phone_pool_info_pool_ids }}"
    validate_certs: true
  register: __pinpoint_sms_voice_phone_pool_info_query

- name: Ensure list of aws end user messaging sms phone pools is generated
  tags:
    - pinpoint_sms_voice_phone_pool_info
  ansible.builtin.set_fact:
    _pinpoint_sms_voice_phone_pool_info_list:
      "{{ __pinpoint_sms_voice_phone_pool_info_query.pools |
          d([]) }}"

- name: Ensure dict of aws end user messaging sms phone pools is generated
  tags:
    - pinpoint_sms_voice_phone_pool_info
  ansible.builtin.set_fact:
    _pinpoint_sms_voice_phone_pool_info_dict:
      "{{ dict(_pinpoint_sms_voice_phone_pool_info_list |
               json_query('[].tags.Name') |
               zip(_pinpoint_sms_voice_phone_pool_info_list)) }}"
...
