---
- name: Ensure information about aws virtual private cloud prefix lists is gathered
  tags:
    - ec2_vpc_prefix_list_info
  linuxhq.aws.ec2_vpc_prefix_list_info:
    filters: "{{ ec2_vpc_prefix_list_info_filters }}"
    prefix_list_ids: "{{ ec2_vpc_prefix_list_info_prefix_list_ids or omit }}"
    target_version: "{{ ec2_vpc_prefix_list_info_target_version or omit }}"
    validate_certs: true
  register: __ec2_vpc_prefix_list_info_query

- name: Ensure list of aws virtual private cloud prefix lists is generated
  tags:
    - ec2_vpc_prefix_list_info
  ansible.builtin.set_fact:
    _ec2_vpc_prefix_list_info_list:
      "{{ __ec2_vpc_prefix_list_info_query.prefix_lists |
          d([]) }}"

- name: Ensure dict of aws virtual private cloud prefix lists is generated
  tags:
    - ec2_vpc_prefix_list_info
  ansible.builtin.set_fact:
    _ec2_vpc_prefix_list_info_dict:
      "{{ dict(_ec2_vpc_prefix_list_info_list |
               json_query('[].prefix_list_name') |
               zip(_ec2_vpc_prefix_list_info_list)) }}"
...
