---
- name: Ensure information about aws eks clusters is gathered
  tags:
    - eks_cluster_info
  linuxhq.aws.eks_cluster_info:
    name: "{{ eks_cluster_info_name or omit }}"
    validate_certs: true
  register: __eks_cluster_info_query

- name: Ensure list of aws eks cluster information is generated
  tags:
    - eks_cluster_info
  ansible.builtin.set_fact:
    _eks_cluster_info_list:
      "{{ __eks_cluster_info_query.clusters |
          d([]) }}"

- name: Ensure dict of aws eks cluster information is generated
  tags:
    - eks_cluster_info
  ansible.builtin.set_fact:
    _eks_cluster_info_dict:
      "{{ dict(_eks_cluster_info_list |
               json_query('[].name') |
               zip(_eks_cluster_info_list)) }}"
...
