---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - aws_caller_info

    - role: s3_bucket
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ec2_vpc_net
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ec2_vpc_subnet
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ec2_transit_gateway
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ec2_transit_gateway_vpc_attachment
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ec2_flow_log
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - ec2_flow_log_info
...
