---
- name: Ensure elastic kubernetes service clusters are managed
  tags:
    - eks_cluster
  community.aws.eks_cluster:
    name: "{{ _cluster.name }}"
    role_arn: "{{ __eks_cluster_iam_role_arn | d(omit) }}"
    security_groups: "{{ __eks_cluster_security_group | d(omit) }}"
    state: "{{ _cluster.state }}"
    subnets: "{{ _cluster.subnets }}"
    tags:
      "{{ _cluster.tags |
          d({}) |
          combine({'Name': _cluster.name}) }}"
    validate_certs: true
    version: "{{ _cluster.version }}"
    wait: "{{ _cluster.wait | d(false) }}"
    wait_timeout: "{{ _cluster.wait_timeout | d(1200) }}"
  when:
    - not ansible_check_mode
...
