---
- name: Ensure aws elastic kubernetes service clusters are batched
  tags:
    - eks_cluster
  ansible.builtin.include_tasks:
    apply:
      tags:
        - eks_cluster
    file: include.yml
  loop:
    "{{ eks_cluster_list |
        batch(eks_cluster_batch) }}"
  loop_control:
    label: "{{ __eks_cluster_list | length }}"
    loop_var: __eks_cluster_list
...
