---
- name: Ensure elastic kubernetes service security groups are managed
  tags:
    - eks_cluster
  amazon.aws.ec2_security_group:
    description: "{{ _cluster.description | d(_cluster.name) }}"
    name: "{{ _cluster.name }}"
    purge_rules: true
    purge_rules_egress: true
    purge_tags: true
    rules: "{{ _cluster.rules | d(__eks_cluster_rules) }}"
    rules_egress: "{{ _cluster.rules_egress | d(__eks_cluster_rules_egress) }}"
    state: "{{ _cluster.state | d('present') }}"
    tags:
      "{{ _cluster.tags |
          d({}) |
          combine({'Name': _cluster.name}) }}"
    validate_certs: true
    vpc_id: "{{ _cluster.vpc_id }}"
  register: __eks_cluster_security_group_result
  until:
    - __eks_cluster_security_group_result is success
  delay: 5
  retries: 60

- name: Ensure list of elastic kubernetes service security group is generated
  tags:
    - eks_cluster
  ansible.builtin.set_fact:
    __eks_cluster_security_group:
      "{{ [__eks_cluster_security_group_result.group_id] }}"
  when:
    - _cluster.state == 'present'
    - not ansible_check_mode
...
