---
- name: Ensure aws route53 resolver rules are managed
  tags:
    - route53_resolver_rule
  linuxhq.aws.route53_resolver_rule:
    domain_name: "{{ _resolver_rule.domain_name }}"
    name: "{{ _resolver_rule.name }}"
    resolver_endpoint_id: "{{ _resolver_rule.resolver_endpoint_id }}"
    rule_type: "{{ _resolver_rule.rule_type }}"
    state: "{{ _resolver_rule.state | d('present') }}"
    target_ips: "{{ _resolver_rule.target_ips }}"
    validate_certs: true
    wait: "{{ _resolver_rule.wait | d(true) }}"
    wait_delay: 5
    wait_timeout: 300
  register: __route53_resolver_rule_result
  loop: "{{ __route53_resolver_rule_list }}"
  loop_control:
    label: "{{ _resolver_rule.name | d(none) }}"
    loop_var: _resolver_rule
  async: "{{ ansible_check_mode | ternary(0, route53_resolver_rule_async) }}"
  poll: "{{ route53_resolver_rule_poll }}"
  when:
    - _resolver_rule.name is defined
    - _resolver_rule.domain_name is defined
    - _resolver_rule.resolver_endpoint_id is defined
    - _resolver_rule.rule_type is defined
    - _resolver_rule.target_ips is defined
    - _resolver_rule.target_ips | length > 0
  changed_when:
    - ansible_check_mode | bool
    - __route53_resolver_rule_result.changed | bool

- name: Ensure managed aws route53 resolver rule jobs are complete
  tags:
    - route53_resolver_rule
  ansible.builtin.async_status:
    jid: "{{ _jid.ansible_job_id }}"
  register: __route53_resolver_rule_status
  loop: "{{ __route53_resolver_rule_result.results }}"
  loop_control:
    label: "{{ _jid._resolver_rule.name | d(none) }}"
    loop_var: _jid
  delay: "{{ route53_resolver_rule_delay }}"
  retries: "{{ route53_resolver_rule_retries }}"
  when:
    - _jid.ansible_job_id is defined
  until:
    - __route53_resolver_rule_status.finished | bool
...
