---
- name: Ensure aws route53 resolver rule defaults are present
  tags:
    - route53_resolver_rule
  ansible.builtin.set_fact:
    __route53_resolver_rule_list:
      "{{ [{'state': 'present'}] |
          product(route53_resolver_rule_list) |
          map('combine') |
          list }}"

- name: Ensure list of aws route53 resolver rules is gathered
  tags:
    - route53_resolver_rule
  ansible.builtin.command:
    cmd: >
      aws route53resolver list-resolver-rules
        --query 'ResolverRules[].{key: Name, value: Id}'
  register: __route53_resolver_rule_query
  changed_when: false
  check_mode: false

- name: Ensure dict of aws route53 resolver rules is generated
  tags:
    - route53_resolver_rule
  ansible.builtin.set_fact:
    __route53_resolver_rule_dict:
      "{{ (__route53_resolver_rule_query.stdout |
          from_json) |
          items2dict }}"

- name: Ensure aws route53 resolver rule tasks are included
  tags:
    - route53_resolver_rule
  ansible.builtin.include_tasks:
    apply:
      tags:
        - route53_resolver_rule
    file: include.yml
  loop: "{{ __route53_resolver_rule_list }}"
  loop_control:
    label: "{{ _resolver_rule.name | d(none) }}"
    loop_var: _resolver_rule
  when:
    - _resolver_rule.name is defined
    - _resolver_rule.domain_name is defined
    - _resolver_rule.resolver_endpoint_id is defined
    - _resolver_rule.rule_type is defined
    - _resolver_rule.target_ips is defined
    - _resolver_rule.target_ips | length > 0
...
