---
- name: Ensure aws route53 resolver rules are batched
  tags:
    - route53_resolver_rule
  ansible.builtin.include_tasks:
    apply:
      tags:
        - route53_resolver_rule
    file: include.yml
  loop:
    "{{ route53_resolver_rule_list |
        batch(route53_resolver_rule_batch) }}"
  loop_control:
    label: "{{ __route53_resolver_rule_list | length }}"
    loop_var: __route53_resolver_rule_list
...
