---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: rds_option_group
      rds_option_group_list: []
      tags:
        - molecule-idempotence-notest

    - rds_option_group
...
