---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: route53_delegation_set
      route53_delegation_set_list: []
      tags:
        - molecule-idempotence-notest

    - route53_delegation_set
...
