---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: wafv2_web_acl
      wafv2_web_acl_list: []
      tags:
        - molecule-idempotence-notest

    - role: wafv2_web_acl
      tags:
        - molecule-idempotence-notest

    - role: wafv2_web_acl
      wafv2_web_acl_list: "{{ wafv2_web_acl_updated_list }}"
...
