---
- name: Ensure information about aws secrets manager regions is gathered
  tags:
    - secretsmanager_secret_info
  amazon.aws.aws_az_info:
    validate_certs: true
  register: __secretsmanager_secret_info_az
  check_mode: false

- name: Ensure string of aws secrets manager region is generated
  tags:
    - secretsmanager_secret_info
  ansible.builtin.set_fact:
    __secretsmanager_secret_info_region:
      "{{ __secretsmanager_secret_info_az.availability_zones.0.region_name }}"

- name: Ensure list of aws secrets manager secrets is generated
  tags:
    - secretsmanager_secret_info
  ansible.builtin.set_fact:
    _secretsmanager_secret_info_list:
      "{{ _secretsmanager_secret_info_list |
          d([]) +
          [{'name': _secret.name,
            'value': __secretsmanager_secret_info_lookup}] }}"
  register: _secretsmanager_secret_info_result
  loop: "{{ secretsmanager_secret_info_list }}"
  loop_control:
    label: "{{ _secret.name | d(none) }}"
    loop_var: _secret
  when:
    - _secret.name is defined
  vars:
    __secretsmanager_secret_info_lookup:
      "{{ lookup('amazon.aws.secretsmanager_secret',
                 _secret.name,
                 bypath=_secret.bypath | d(false),
                 nested=_secret.nested | d(false),
                 on_deleted=secretsmanager_secret_info_on_deleted,
                 on_denied=secretsmanager_secret_info_on_denied,
                 on_missing=secretsmanager_secret_info_on_missing,
                 region=__secretsmanager_secret_info_region) }}"

- name: Ensure empty list of aws secrets manager secrets is generated
  tags:
    - secretsmanager_secret_info
  ansible.builtin.set_fact:
    _secretsmanager_secret_info_list: []
  when:
    - _secretsmanager_secret_info_result is skipped

- name: Ensure dict of aws secrets manager secrets is generated
  tags:
    - secretsmanager_secret_info
  ansible.builtin.set_fact:
    _secretsmanager_secret_info_dict:
      "{{ dict(_secretsmanager_secret_info_list |
               json_query('[].name') |
               zip(_secretsmanager_secret_info_list)) }}"
...
