---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: cloudwatchlogs_log_group
      cloudwatchlogs_log_group_list: []
      tags:
        - molecule-idempotence-notest

    - cloudwatchlogs_log_group
...
