---
- name: Ensure aws wafv2 ip sets are batched
  tags:
    - wafv2_ip_set
  ansible.builtin.include_tasks:
    apply:
      tags:
        - wafv2_ip_set
    file: include.yml
  loop:
    "{{ wafv2_ip_set_list |
        batch(wafv2_ip_set_batch) }}"
  loop_control:
    label: "{{ __wafv2_ip_set_list | length }}"
    loop_var: __wafv2_ip_set_list
...
