---
- name: Ensure aws systems manager associations are batched
  tags:
    - ssm_association
  ansible.builtin.include_tasks:
    apply:
      tags:
        - ssm_association
    file: include.yml
  loop:
    "{{ ssm_association_list |
        batch(ssm_association_batch) }}"
  loop_control:
    label: "{{ __ssm_association_list | length }}"
    loop_var: __ssm_association_list
...
