---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - ses_sandbox_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _ses_sandbox_info_dict.dedicated_ip_auto_warmup_enabled | bool
          - _ses_sandbox_info_dict.details.additional_contact_email_addresses.0 ==
              ses_sandbox_additional_contact_email_addresses.0
          - _ses_sandbox_info_dict.details.additional_contact_email_addresses.1 ==
              ses_sandbox_additional_contact_email_addresses.1
          - _ses_sandbox_info_dict.details.contact_language == 'EN'
          - _ses_sandbox_info_dict.details.mail_type == 'TRANSACTIONAL'
          - _ses_sandbox_info_dict.details.review_details.case_id is defined
          - _ses_sandbox_info_dict.details.review_details.status is defined
          - _ses_sandbox_info_dict.details.use_case_description is defined
          - _ses_sandbox_info_dict.details.website_url ==
              ses_sandbox_website_url
          - _ses_sandbox_info_dict.enforcement_status is defined
          - _ses_sandbox_info_dict.production_access_enabled is defined
          - _ses_sandbox_info_dict.send_quota is defined
          - _ses_sandbox_info_dict.sending_enabled | bool
          - _ses_sandbox_info_dict.suppression_attributes is defined
...
