---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: account_region
      account_region_list: []
      tags:
        - molecule-idempotence-notest

    - account_region
...
