---
- name: Ensure aws key management service keys are batched
  tags:
    - kms_key
  ansible.builtin.include_tasks:
    apply:
      tags:
        - kms_key
    file: include.yml
  loop:
    "{{ kms_key_list |
        batch(kms_key_batch) }}"
  loop_control:
    label: "{{ __kms_key_list | length }}"
    loop_var: __kms_key_list
...
