---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

platforms:
  - name: localhost

provisioner:
  name: ansible
  log: true
  env:
    ANSIBLE_ACTION_WARNINGS: false
    ANSIBLE_DEPRECATION_WARNINGS: false
  options:
    diff: true
  inventory:
    group_vars:
      all:
        iam_account_alias_name: "molecule-{{ ansible_facts.date_time.date }}"

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
