---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: ssm_parameter
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ssm_parameter_info
      ssm_parameter_info_list: []
      tags:
        - molecule-idempotence-notest

    - ssm_parameter_info
...
