---
- name: Ensure aws notifications contacts are batched
  tags:
    - notifications_contacts
  ansible.builtin.include_tasks:
    apply:
      tags:
        - notifications_contacts
    file: include.yml
  loop:
    "{{ notifications_contacts_list |
        batch(notifications_contacts_batch) }}"
  loop_control:
    label: "{{ __notifications_contacts_list | length }}"
    loop_var: __notifications_contacts_list
...
