---
- name: Ensure information about aws route53 resolver rules is gathered
  tags:
    - route53_resolver_rule_info
  linuxhq.aws.route53_resolver_rule_info:
    filters: "{{ route53_resolver_rule_info_filters }}"
    validate_certs: true
  register: __route53_resolver_rule_info_query

- name: Ensure list of aws route53 resolver rules is generated
  tags:
    - route53_resolver_rule_info
  ansible.builtin.set_fact:
    _route53_resolver_rule_info_list:
      "{{ __route53_resolver_rule_info_query.resolver_rules |
          d([]) }}"

- name: Ensure dict of aws route53 resolver rules is generated
  tags:
    - route53_resolver_rule_info
  ansible.builtin.set_fact:
    _route53_resolver_rule_info_dict:
      "{{ dict(_route53_resolver_rule_info_list |
               json_query('[].name') |
               zip(_route53_resolver_rule_info_list)) }}"
...
