---
dependencies: []
galaxy_info:
  role_name: sns_sms_attributes
  author: Taylor Kimball
  description: Manage aws simple notification service sms attributes
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - notification
    - service
    - simple
    - sms
...
