---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - rds_instance_param_group_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _rds_instance_param_group_info_dict['mariadb106'].db_parameter_group_arn is defined
          - _rds_instance_param_group_info_dict['mariadb106'].db_parameter_group_family is defined
          - _rds_instance_param_group_info_dict['mariadb106'].db_parameter_group_name is defined
          - _rds_instance_param_group_info_dict['mariadb114'].db_parameter_group_arn is defined
          - _rds_instance_param_group_info_dict['mariadb114'].db_parameter_group_family is defined
          - _rds_instance_param_group_info_dict['mariadb114'].db_parameter_group_name is defined
          - _rds_instance_param_group_info_dict['mariadb118'].db_parameter_group_arn is defined
          - _rds_instance_param_group_info_dict['mariadb118'].db_parameter_group_family is defined
          - _rds_instance_param_group_info_dict['mariadb118'].db_parameter_group_name is defined

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        rds_instance_param_group_list:
          "{{ rds_instance_param_group_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _verify }}"
      loop:
        - rds_instance_param_group
      loop_control:
        label: "{{ _verify }}"
        loop_var: _verify
...
