---
- name: Ensure aws systems manager association information is gathered
  tags:
    - ssm_association_info
  linuxhq.aws.ssm_association_info:
    validate_certs: true
  register: __ssm_association_info_query

- name: Ensure list of aws systems manager association information is generated
  tags:
    - ssm_association_info
  ansible.builtin.set_fact:
    _ssm_association_info_list:
      "{{ __ssm_association_info_query.associations |
          d([]) }}"

- name: Ensure dict of aws systems manager association information is generated
  tags:
    - ssm_association_info
  ansible.builtin.set_fact:
    _ssm_association_info_dict:
      "{{ dict(_ssm_association_info_list |
               json_query('[].name') |
               zip(_ssm_association_info_list)) }}"
...
