---
allow_duplicates: true
dependencies: []
galaxy_info:
  role_name: elb_application_lb_info
  author: Taylor Kimball
  description: Gather information about elastic load balancer application load balancers
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - application
    - aws
    - balancer
    - elb
    - info
    - load
...
