---
- name: Ensure aws route53 zone associations are managed
  tags:
    - route53_zone_associate
  linuxhq.aws.route53_zone_associate:
    hosted_zone_id: "{{ _zone.hosted_zone_id }}"
    state: "{{ _zone.state | d('present') }}"
    validate_certs: true
    vpc_id: "{{ _zone.vpc_id }}"
    vpc_region: "{{ _zone.vpc_region }}"
  register: __route53_zone_associate_result
  loop: "{{ __route53_zone_associate_list }}"
  loop_control:
    label: "{{ _zone.hosted_zone_id | d(none) }}"
    loop_var: _zone
  async: "{{ ansible_check_mode | ternary(0, route53_zone_associate_async) }}"
  poll: "{{ route53_zone_associate_poll }}"
  when:
    - _zone.hosted_zone_id is defined
    - _zone.vpc_id is defined
    - _zone.vpc_region is defined
  changed_when:
    - ansible_check_mode | bool
    - __route53_zone_associate_result.changed | bool

- name: Ensure managed aws route53 zone association jobs are complete
  tags:
    - route53_zone_associate
  ansible.builtin.async_status:
    jid: "{{ _jid.ansible_job_id }}"
  register: __route53_zone_associate_status
  loop: "{{ __route53_zone_associate_result.results }}"
  loop_control:
    label: "{{ _jid._zone.hosted_zone_id | d(none) }}"
    loop_var: _jid
  delay: "{{ route53_zone_associate_delay }}"
  retries: "{{ route53_zone_associate_retries }}"
  when:
    - _jid.ansible_job_id is defined
  until:
    - __route53_zone_associate_status.finished | bool
...
