---
- name: Ensure aws route53 zone assocation variables are generated
  tags:
    - route53_zone_associate
  ansible.builtin.set_fact:
    __route53_zone_associate_json:
      VPCId: "{{ _zone.vpc_id }}"
      VPCRegion: "{{ _zone.vpc_region }}"
    __route53_zone_associate_state:
      "{{ __route53_zone_associate_dict[_zone.hosted_zone_id] |
          map(attribute='VPCId', default=[]) }}"

- name: Ensure aws route53 zone associations are present
  tags:
    - route53_zone_associate
  ansible.builtin.command:
    cmd: >
      aws route53 associate-vpc-with-hosted-zone
        --hosted-zone-id "{{ _zone.hosted_zone_id }}"
        --vpc '{{ __route53_zone_associate_json | to_json }}'
  when:
    - _zone.state == 'present'
    - _zone.vpc_id not in __route53_zone_associate_state
  changed_when: true

- name: Ensure aws route53 zone associations are absent
  tags:
    - route53_zone_associate
  ansible.builtin.command:
    cmd: >
      aws route53 disassociate-vpc-from-hosted-zone
        --hosted-zone-id "{{ _zone.hosted_zone_id }}"
        --vpc '{{ __route53_zone_associate_json | to_json }}'
  when:
    - _zone.state == 'absent'
    - _zone.vpc_id in __route53_zone_associate_state
  changed_when: true
...
