---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: route53_delegation_set
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - route53_delegation_set_info
...
