---
route53_resolver_rule_async: 300
route53_resolver_rule_batch: 10
route53_resolver_rule_delay: 3
route53_resolver_rule_list: []
route53_resolver_rule_poll: 0
route53_resolver_rule_retries: 100
...
