---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: ec2_vpc_net
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: route53_zone
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: route53_record
      tags:
        - molecule-idempotence-notest

    - role: route53_record
      route53_record_list: "{{ route53_record_updated_list }}"
...
