---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: aws_caller_info
      check_mode: false

    - role: iam_role
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ec2_vpc_net
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ec2_vpc_igw
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: ec2_vpc_subnet
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: rds_instance_param_group
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: rds_option_group
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: rds_subnet_group
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: rds_instance
      rds_instance_list: []
      tags:
        - molecule-idempotence-notest

    - rds_instance
...
