---
- name: Verify
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - aws_caller_info
    - ec2_vpc_net_info
    - ec2_vpc_subnet_info

  post_tasks:
    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        ec2_vpc_igw_list:
          "{{ ec2_vpc_igw_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_vpc_net_list:
          "{{ ec2_vpc_net_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_vpc_subnet_list:
          "{{ ec2_vpc_subnet_list |
              map('combine', {'state': 'absent'}) }}"
        iam_role_list:
          "{{ iam_role_list |
              map('combine', {'state': 'absent'}) }}"
        rds_instance_list:
          "{{ rds_instance_list |
              map('combine',
                  {'state': 'absent', 'wait': true}) }}"
        rds_instance_param_group_list:
          "{{ rds_instance_param_group_list |
              map('combine', {'state': 'absent'}) }}"
        rds_option_group_list:
          "{{ rds_option_group_list |
              map('combine', {'state': 'absent'}) }}"
        rds_subnet_group_list:
          "{{ rds_subnet_group_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _role }}"
      loop:
        - rds_instance
        - rds_subnet_group
        - rds_option_group
        - rds_instance_param_group
        - ec2_vpc_subnet
        - ec2_vpc_igw
        - ec2_vpc_net
        - iam_role
      loop_control:
        label: "{{ _role }}"
        loop_var: _role
...
