---
- name: Ensure aws relational database service instance parameter groups are managed
  tags:
    - rds_instance_param_group
  amazon.aws.rds_instance_param_group:
    description: "{{ _pg.description | d(_pg.name) }}"
    engine: "{{ _pg.engine }}"
    immediate: "{{ _pg.immediate | d(omit) }}"
    name: "{{ _pg.name }}"
    params: "{{ _pg.params }}"
    purge_tags: "{{ _pg.purge_tags | d(true) }}"
    state: "{{ _pg.state | d('present') }}"
    tags:
      "{{ _pg.tags |
          d({}) |
          combine({'Name': _pg.name}) }}"
    validate_certs: true
  register: __rds_instance_param_group_result
  loop: "{{ __rds_instance_param_group_list }}"
  loop_control:
    label: "{{ _pg.name | d(none) }}"
    loop_var: _pg
  when:
    - _pg.engine is defined
    - _pg.name is defined
    - _pg.params is defined
    - _pg.params | length > 0
  changed_when: false
  async: "{{ ansible_check_mode | ternary(0, rds_instance_param_group_async) }}"
  poll: "{{ rds_instance_param_group_poll }}"

- name: Ensure managed relational database service instance parameter groups jobs are complete
  tags:
    - rds_instance_param_group
  ansible.builtin.async_status:
    jid: "{{ _jid.ansible_job_id }}"
  register: __rds_instance_param_group_status
  loop: "{{ __rds_instance_param_group_result.results }}"
  loop_control:
    label: "{{ _jid._pg.name | d(none) }}"
    loop_var: _jid
  when:
    - _jid.ansible_job_id is defined
  until:
    - __rds_instance_param_group_status.finished | bool
  retries: "{{ rds_instance_param_group_retries }}"
  delay: "{{ rds_instance_param_group_delay }}"
...
