---
- name: Ensure information about aws iam inline policies is gathered
  tags:
    - iam_policy_info
  linuxhq.aws.iam_policy_info:
    group_names: "{{ iam_policy_info_group_names or omit }}"
    path_prefix: "{{ iam_policy_info_path_prefix or omit }}"
    policy_names: "{{ iam_policy_info_policy_names or omit }}"
    user_names: "{{ iam_policy_info_user_names or omit }}"
    validate_certs: true
  register: __iam_policy_info_query

- name: Ensure list of aws iam group inline policies is generated
  tags:
    - iam_policy_info
  ansible.builtin.set_fact:
    _iam_policy_info_group_list:
      "{{ __iam_policy_info_query.group_policies |
          d([]) }}"

- name: Ensure list of aws iam user inline policies is generated
  tags:
    - iam_policy_info
  ansible.builtin.set_fact:
    _iam_policy_info_user_list:
      "{{ __iam_policy_info_query.user_policies |
          d([]) }}"

- name: Ensure dict of aws iam group inline policy information is generated
  tags:
    - iam_policy_info
  ansible.builtin.set_fact:
    _iam_policy_info_group_dict:
      "{{ dict(_iam_policy_info_group_list |
               json_query('[].name') |
               zip(_iam_policy_info_group_list)) }}"

- name: Ensure dict of aws iam user inline policy information is generated
  tags:
    - iam_policy_info
  ansible.builtin.set_fact:
    _iam_policy_info_user_dict:
      "{{ dict(_iam_policy_info_user_list |
               json_query('[].name') |
               zip(_iam_policy_info_user_list)) }}"
...
