---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  tasks:
    - name: Ensure splunk addon resources are absent
      ansible.builtin.include_role:
        name: splunk_addon
      vars:
        splunk_addon_state: absent
...
