---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

platforms:
  - name: localhost

provisioner:
  name: ansible
  env:
    ANSIBLE_ACTION_WARNINGS: false
    ANSIBLE_DEPRECATION_WARNINGS: false
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        iam_role_list:
          - name: molecule-role-ec2
            assume_role_policy_document:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    Service: ec2.amazonaws.com
                  Action:
                    - sts:AssumeRole
            create_instance_profile: false
            managed_policies:
              - AmazonEC2ReadOnlyAccess
          - name: molecule-role-vpc
            assume_role_policy_document:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    Service: ec2.amazonaws.com
                  Action:
                    - sts:AssumeRole
            create_instance_profile: false
            managed_policies:
              - AmazonVPCReadOnlyAccess

        iam_instance_profile_list:
          - name: molecule-instance-profile-ec2
            role: molecule-role-ec2
          - name: molecule-instance-profile-vpc
            role: molecule-role-vpc

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
