---
- name: Converge
  hosts: all
  roles:
    - role: ec2_vpc_dhcp_option
      ec2_vpc_dhcp_option_list: []
      tags:
        - molecule-idempotence-notest

    - ec2_vpc_dhcp_option

  post_tasks:
    - name: Ensure aws virtual private cloud dhcp options are discoverable
      amazon.aws.ec2_vpc_dhcp_option_info:
        filters:
          tag:Name:
            "{{ ec2_vpc_dhcp_option_list | map(attribute='name') }}"
      register: _ec2_vpc_dhcp_option_molecule_info
      changed_when: false
      delay: 3
      retries: 20
      until:
        - _ec2_vpc_dhcp_option_molecule_info.dhcp_options | length >=
          ec2_vpc_dhcp_option_list | length
      when:
        - not ansible_check_mode
...
