---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: ec2_vpc_dhcp_option
      ec2_vpc_dhcp_option_list: []
      tags:
        - molecule-idempotence-notest

    - ec2_vpc_dhcp_option
...
