---
- name: Ensure aws service quota value is gathered
  tags:
    - service_quota
  ansible.builtin.command:
    cmd: >
      aws service-quotas get-service-quota
        --output text
        --query Quota.Value
        --quota-code "{{ _servicequota.1.quota_code }}"
        --region "{{ _servicequota.1.region | d(__service_quota_region) }}"
        --service-code "{{ _servicequota.0.service_code }}"
  register: __service_quota_value
  changed_when: false
  check_mode: false

- name: Ensure aws service quota request is managed
  tags:
    - service_quota
  ansible.builtin.command:
    cmd: >
      aws service-quotas request-service-quota-increase
        --desired-value '{{ _servicequota.1.value }}'
        --quota-code "{{ _servicequota.1.quota_code }}"
        --region "{{ _servicequota.1.region | d(__service_quota_region) }}"
        --service-code "{{ _servicequota.0.service_code }}"
  when:
    - _servicequota.1.value | float > __service_quota_value.stdout | float
  changed_when: true
...
