---
- name: Ensure information about aws service quota availability zones is gathered
  tags:
    - service_quota
  amazon.aws.aws_az_info:
    validate_certs: true
  register: __service_quota_availability_zone

- name: Ensure string of aws service quota region is generated
  tags:
    - service_quota
  ansible.builtin.set_fact:
    __service_quota_region:
      "{{ __service_quota_availability_zone.availability_zones.0.region_name }}"

- name: Ensure aws service quotas are batched
  tags:
    - service_quota
  ansible.builtin.include_tasks:
    apply:
      tags:
        - service_quota
    file: include.yml
  loop:
    "{{ service_quota_list |
        batch(service_quota_batch) }}"
  loop_control:
    label: "{{ __service_quota_list | length }}"
    loop_var: __service_quota_list
...
