---
- name: Ensure information about aws service quota availability zone is gathered
  tags:
    - service_quota
  amazon.aws.aws_az_info:
    validate_certs: true
  register: __service_quota_availability_zone

- name: Ensure string of aws service quota region is generated
  tags:
    - service_quota
  ansible.builtin.set_fact:
    __service_quota_region:
      "{{ __service_quota_availability_zone.availability_zones.0.region_name }}"

- name: Ensure aws service quotas are managed
  tags:
    - service_quota
  linuxhq.aws.service_quota:
    quota_code: "{{ _servicequota.1.quota_code }}"
    region: "{{ _servicequota.1.region | d(__service_quota_region) }}"
    service_code: "{{ _servicequota.0.service_code }}"
    validate_certs: true
    value: "{{ _servicequota.1.value }}"
  loop:
    "{{ q('ansible.builtin.subelements',
          service_quota_list,
          'quotas',
          {'skip_missing': true}) }}"
  loop_control:
    label: "{{ _servicequota.1.quota_code | d(none) }}"
    loop_var: _servicequota
  when:
    - _servicequota.0.service_code is defined
    - _servicequota.1.quota_code is defined
    - _servicequota.1.value is defined
...
