---
- name: Ensure aws account region opt-in status is disabled
  tags:
    - account_region
  ansible.builtin.command:
    cmd: >
      aws account disable-region
        --region-name "{{ _region.name }}"
  changed_when: true

- name: Ensure aws account region opt-in status is absent
  tags:
    - account_region
  amazon.aws.aws_region_info:
    filters:
      region-name: "{{ _region.name }}"
  register: __account_region_disable
  when:
    - account_region_wait | bool
    - not ansible_check_mode
  until:
    - __account_region_disable.regions.0 is not defined
  delay: "{{ account_region_delay }}"
  retries: "{{ account_region_retries }}"
...
