---
- name: Ensure aws account regions are batched
  tags:
    - account_region
  ansible.builtin.include_tasks:
    apply:
      tags:
        - account_region
    file: include.yml
  loop:
    "{{ account_region_list |
        batch(account_region_batch) }}"
  loop_control:
    label: "{{ __account_region_list | length }}"
    loop_var: __account_region_list
...
