---
- name: Converge
  hosts: all
  roles:
    - role: ssm_association
      ssm_association_list: []
      tags:
        - molecule-idempotence-notest

    - role: ssm_association
      ssm_association_list:
        "{{ ssm_association_list_create }}"
      tags:
        - molecule-idempotence-notest

    - role: ssm_association
      ssm_association_list:
        "{{ ssm_association_list_update }}"
...
