---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  pre_tasks:
    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        ssm_association_list:
          "{{ ssm_association_list_update |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - ssm_association
...
