---
- name: Converge
  hosts: all
  environment:
    PATH: "/opt/awscli/bin:{{ ansible_env.PATH }}"

  roles:
    - role: acm_certificate
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - acm_certificate_info
...
