---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - aws_caller_info
    - ec2_security_group_info
    - ec2_vpc_net_info
    - ec2_vpc_subnet_info

  post_tasks:
    - name: Ensure role is included without filters or name
      ansible.builtin.include_role:
        name: eks_cluster_info

    - name: Ensure info without filters or name is verified
      ansible.builtin.assert:
        that:
          - _eks_cluster_info_dict['molecule-eks1'].arn is defined
          - _eks_cluster_info_dict['molecule-eks1'].endpoint is defined
          - _eks_cluster_info_dict['molecule-eks1'].resources_vpc_config.endpoint_public_access
          - _eks_cluster_info_dict['molecule-eks1'].status == 'ACTIVE'
          - _eks_cluster_info_dict['molecule-eks1'].version == '1.34'
          - _eks_cluster_info_dict['molecule-eks2'].arn is defined
          - _eks_cluster_info_dict['molecule-eks2'].endpoint is defined
          - _eks_cluster_info_dict['molecule-eks2'].resources_vpc_config.endpoint_private_access
          - _eks_cluster_info_dict['molecule-eks2'].status == 'ACTIVE'
          - _eks_cluster_info_dict['molecule-eks2'].version == '1.35'

    - name: Ensure role is included with one name
      ansible.builtin.include_role:
        name: eks_cluster_info
      vars:
        eks_cluster_info_name: "{{ eks_cluster_list.0.name }}"

    - name: Ensure info with one name is verified
      ansible.builtin.assert:
        that:
          - _eks_cluster_info_list | length == 1
          - _eks_cluster_info_list.0.name == eks_cluster_list.0.name
          - _eks_cluster_info_dict.keys() | list == [eks_cluster_list.0.name]
          - _eks_cluster_info_dict[eks_cluster_list.0.name].arn is defined
          - _eks_cluster_info_dict[eks_cluster_list.0.name].endpoint is defined
          - _eks_cluster_info_dict[eks_cluster_list.0.name].resources_vpc_config.endpoint_public_access
          - _eks_cluster_info_dict[eks_cluster_list.0.name].status == 'ACTIVE'
          - _eks_cluster_info_dict[eks_cluster_list.0.name].version == '1.34'

    - name: Ensure role is included with filters
      ansible.builtin.include_role:
        name: eks_cluster_info
      vars:
        eks_cluster_info_filters:
          name: "{{ eks_cluster_list.1.name }}"

    - name: Ensure info with filters is verified
      ansible.builtin.assert:
        that:
          - _eks_cluster_info_list | length == 1
          - _eks_cluster_info_list.0.name == eks_cluster_list.1.name
          - _eks_cluster_info_dict.keys() | list == [eks_cluster_list.1.name]
          - _eks_cluster_info_dict[eks_cluster_list.1.name].resources_vpc_config.endpoint_private_access
          - _eks_cluster_info_dict[eks_cluster_list.1.name].version == '1.35'

    - name: Ensure role is included with another name
      ansible.builtin.include_role:
        name: eks_cluster_info
      vars:
        eks_cluster_info_name: "{{ eks_cluster_list.1.name }}"

    - name: Ensure info with another name is verified
      ansible.builtin.assert:
        that:
          - _eks_cluster_info_list | length == 1
          - _eks_cluster_info_list.0.name == eks_cluster_list.1.name
          - _eks_cluster_info_dict.keys() | list == [eks_cluster_list.1.name]
          - _eks_cluster_info_dict[eks_cluster_list.1.name].resources_vpc_config.endpoint_private_access
          - _eks_cluster_info_dict[eks_cluster_list.1.name].version == '1.35'

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        ec2_security_group_list:
          - vpc_id: "{{ _ec2_vpc_net_info_dict['molecule'].id }}"
            security_groups:
              "{{ ec2_security_group_list.0.security_groups |
                  map('combine', {'state': 'absent'}) }}"
        ec2_vpc_net_list:
          "{{ ec2_vpc_net_list |
              map('combine', {'state': 'absent'}) }}"
        ec2_vpc_subnet_list:
          "{{ ec2_vpc_subnet_list |
              map('combine', {'state': 'absent'}) }}"
        eks_cluster_list:
          "{{ eks_cluster_list |
              map('combine', {'state': 'absent'}) }}"
        iam_role_list:
          "{{ iam_role_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _verify }}"
      loop:
        - eks_cluster
        - ec2_security_group
        - ec2_vpc_subnet
        - ec2_vpc_net
        - iam_role
      loop_control:
        label: "{{ _verify }}"
        loop_var: _verify
...
