---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: wafv2_web_acl_info
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - role: wafv2_web_acl
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - wafv2_web_acl_info
...
