---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - wafv2_web_acl_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _wafv2_web_acl_info_dict['molecule-amazonipreputationlist'].arn is defined
          - _wafv2_web_acl_info_dict['molecule-amazonipreputationlist'].id is defined
          - _wafv2_web_acl_info_dict['molecule-amazonipreputationlist'].name is defined
          - _wafv2_web_acl_info_dict['molecule-amazonipreputationlist'].rules is defined
          - _wafv2_web_acl_info_dict['molecule-amazonipreputationlist'].rules | length == 1
          - _wafv2_web_acl_info_dict['molecule-commonruleset'].arn is defined
          - _wafv2_web_acl_info_dict['molecule-commonruleset'].id is defined
          - _wafv2_web_acl_info_dict['molecule-commonruleset'].name is defined
          - _wafv2_web_acl_info_dict['molecule-commonruleset'].rules is defined
          - _wafv2_web_acl_info_dict['molecule-commonruleset'].rules | length == 1
          - _wafv2_web_acl_info_dict['molecule-knownbadinputsruleset'].arn is defined
          - _wafv2_web_acl_info_dict['molecule-knownbadinputsruleset'].id is defined
          - _wafv2_web_acl_info_dict['molecule-knownbadinputsruleset'].name is defined
          - _wafv2_web_acl_info_dict['molecule-knownbadinputsruleset'].rules is defined
          - _wafv2_web_acl_info_dict['molecule-knownbadinputsruleset'].rules | length == 1
          - _wafv2_web_acl_info_dict['molecule-linuxruleset'].arn is defined
          - _wafv2_web_acl_info_dict['molecule-linuxruleset'].id is defined
          - _wafv2_web_acl_info_dict['molecule-linuxruleset'].name is defined
          - _wafv2_web_acl_info_dict['molecule-linuxruleset'].rules is defined
          - _wafv2_web_acl_info_dict['molecule-linuxruleset'].rules | length == 1
          - _wafv2_web_acl_info_dict['molecule-anonymousiplist'].arn is defined
          - _wafv2_web_acl_info_dict['molecule-anonymousiplist'].id is defined
          - _wafv2_web_acl_info_dict['molecule-anonymousiplist'].name is defined
          - _wafv2_web_acl_info_dict['molecule-anonymousiplist'].rules is defined
          - _wafv2_web_acl_info_dict['molecule-anonymousiplist'].rules | length == 1
          - _wafv2_web_acl_info_dict['molecule-sqliruleset'].arn is defined
          - _wafv2_web_acl_info_dict['molecule-sqliruleset'].id is defined
          - _wafv2_web_acl_info_dict['molecule-sqliruleset'].name is defined
          - _wafv2_web_acl_info_dict['molecule-sqliruleset'].rules is defined
          - _wafv2_web_acl_info_dict['molecule-sqliruleset'].rules | length == 1

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        wafv2_web_acl_list:
          "{{ wafv2_web_acl_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _verify }}"
      loop:
        - wafv2_web_acl
      loop_control:
        label: "{{ _verify }}"
        loop_var: _verify
...
