---
- name: Ensure information about aws rds subnet groups is gathered
  tags:
    - rds_subnet_group_info
  linuxhq.aws.rds_subnet_group_info:
    names: "{{ rds_subnet_group_info_names or omit }}"
    validate_certs: true
  register: __rds_subnet_group_info_query

- name: Ensure list of aws rds subnet groups is generated
  tags:
    - rds_subnet_group_info
  ansible.builtin.set_fact:
    _rds_subnet_group_info_list:
      "{{ __rds_subnet_group_info_query.subnet_groups |
          d([]) }}"

- name: Ensure dict of aws rds subnet groups is generated
  tags:
    - rds_subnet_group_info
  ansible.builtin.set_fact:
    _rds_subnet_group_info_dict:
      "{{ dict(_rds_subnet_group_info_list |
               json_query('[].db_subnet_group_name') |
               zip(_rds_subnet_group_info_list)) }}"
...
