---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: acm_certificate
      acm_certificate_list: []
      tags:
        - molecule-idempotence-notest

    - acm_certificate
...
