---
route53_delegation_set_async: 300
route53_delegation_set_batch: 10
route53_delegation_set_delay: 3
route53_delegation_set_list: []
route53_delegation_set_poll: 0
route53_delegation_set_retries: 100
...
