---
- name: Ensure aws wafv2 resources are active
  tags:
    - wafv2_resources
  amazon.aws.elb_application_lb_info:
    load_balancer_arns:
      - "{{ _resource.arn }}"
    validate_certs: true
  register: __wafv2_resources_elb_info
  loop:
    "{{ wafv2_resources_list |
        selectattr('arn', 'defined') |
        selectattr('arn', 'search', ':elasticloadbalancing:') }}"
  loop_control:
    label: "{{ _resource.name | d(none) }}"
    loop_var: _resource
  retries: 30
  delay: 10
  until:
    - __wafv2_resources_elb_info.load_balancers.0.state.code == 'active'
  when:
    - _resource.state | d('present') == 'present'

- name: Ensure aws wafv2 resources are batched
  tags:
    - wafv2_resources
  ansible.builtin.include_tasks:
    apply:
      tags:
        - wafv2_resources
    file: include.yml
  loop:
    "{{ wafv2_resources_list |
        batch(wafv2_resources_batch) }}"
  loop_control:
    label: "{{ __wafv2_resources_list | length }}"
    loop_var: __wafv2_resources_list
...
