---
- name: Ensure aws wafv2 resources are active
  tags:
    - wafv2_resources
  amazon.aws.elb_application_lb_info:
    load_balancer_arns:
      - "{{ _resource.arn }}"
    validate_certs: true
  register: __wafv2_resources_elb_info
  loop:
    "{{ wafv2_resources_list |
        selectattr('arn', 'defined') |
        selectattr('arn', 'search', ':elasticloadbalancing:') }}"
  loop_control:
    label: "{{ _resource.name | d(none) }}"
    loop_var: _resource
  retries: 30
  delay: 10
  until:
    - __wafv2_resources_elb_info.load_balancers.0.state.code == 'active'
  when:
    - _resource.state | d('present') == 'present'

- name: Ensure aws wafv2 resources are managed
  tags:
    - wafv2_resources
  community.aws.wafv2_resources:
    arn: "{{ _resource.arn }}"
    name: "{{ _resource.name }}"
    scope: "{{ _resource.scope | upper }}"
    state: "{{ _resource.state | d('present') }}"
    validate_certs: true
  register: __wafv2_resources_result
  loop: "{{ wafv2_resources_list }}"
  loop_control:
    label: "{{ _resource.name | d(none) }}"
    loop_var: _resource
  delay: "{{ wafv2_resources_delay }}"
  retries: "{{ wafv2_resources_retries }}"
  when:
    - _resource.arn is defined
    - _resource.name is defined
    - _resource.scope is defined
  until:
    - __wafv2_resources_result is succeeded
...
