---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: notifications_contacts
      notifications_contacts_list: []
      tags:
        - molecule-idempotence-notest

    - notifications_contacts
...
