---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: notifications_hub
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - notifications_hub_info
...
