---
ec2_transit_gateway_route_table_async: 600
ec2_transit_gateway_route_table_batch: 10
ec2_transit_gateway_route_table_delay: 3
ec2_transit_gateway_route_table_list: []
ec2_transit_gateway_route_table_poll: 0
ec2_transit_gateway_route_table_retries: 200
...
