---
- name: Ensure aws rds instances are batched
  tags:
    - rds_instance
  ansible.builtin.include_tasks:
    apply:
      tags:
        - rds_instance
    file: include.yml
  loop:
    "{{ rds_instance_list |
        batch(rds_instance_batch) }}"
  loop_control:
    label: "{{ __rds_instance_list | length }}"
    loop_var: __rds_instance_list
...
