---
- name: Ensure information about aws route53 delegation sets is gathered
  tags:
    - route53_delegation_set_info
  linuxhq.aws.route53_delegation_set_info:
    name: "{{ route53_delegation_set_info_name or omit }}"
    validate_certs: true
  register: __route53_delegation_set_info_query

- name: Ensure list of aws route53 delegation sets is generated
  tags:
    - route53_delegation_set_info
  ansible.builtin.set_fact:
    _route53_delegation_set_info_list:
      "{{ __route53_delegation_set_info_query.delegation_sets |
          d([]) }}"

- name: Ensure dict of aws route53 delegation sets is generated
  tags:
    - route53_delegation_set_info
  ansible.builtin.set_fact:
    _route53_delegation_set_info_dict:
      "{{ dict(_route53_delegation_set_info_list |
               json_query('[].caller_reference') |
               zip(_route53_delegation_set_info_list)) }}"
...
