---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9.6
    cpus: 4
    memory: 4096

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /opt/awscli/bin/python
        secretsmanager_secret_list:
          - name: molecule-secret-1
            secret:
              - key: molecule-secret-1
                value: WnvpxzicuneCE7PM7upC7aVNFwYoz7wE
          - name: molecule-secret-2
            secret:
              - key: molecule-secret-2
                value: JUJMm9adCgL7FPtF7qiuHjyXYne7ivbX
              - key: molecule-secret-2a
                value: ggfiFwtaauCRwwNfxJUE3oRjoHr3ETLL

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
