---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  pre_tasks:
    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        secretsmanager_secret_list:
          "{{ secretsmanager_secret_list |
              map('combine', {'state': 'absent'}) }}"

  roles:
    - secretsmanager_secret
...
