---
- name: Ensure aws elastic filesystems are batched
  tags:
    - efs
  ansible.builtin.include_tasks:
    apply:
      tags:
        - efs
    file: include.yml
  loop:
    "{{ efs_list |
        batch(efs_batch) }}"
  loop_control:
    label: "{{ __efs_list | length }}"
    loop_var: __efs_list
...
