---
- name: Ensure information about aws wafv2 web acls is gathered
  tags:
    - wafv2_web_acl_info
  linuxhq.aws.wafv2_web_acl_info:
    ids: "{{ wafv2_web_acl_info_ids or omit }}"
    names: "{{ wafv2_web_acl_info_names or omit }}"
    scope: "{{ wafv2_web_acl_info_scope }}"
    validate_certs: true
  register: __wafv2_web_acl_info_query

- name: Ensure list of aws wafv2 web acls is generated
  tags:
    - wafv2_web_acl_info
  ansible.builtin.set_fact:
    _wafv2_web_acl_info_list:
      "{{ __wafv2_web_acl_info_query.web_acls |
          d([]) }}"

- name: Ensure dict of aws wafv2 web acls is generated
  tags:
    - wafv2_web_acl_info
  ansible.builtin.set_fact:
    _wafv2_web_acl_info_dict:
      "{{ dict(_wafv2_web_acl_info_list |
               json_query('[].name') |
               zip(_wafv2_web_acl_info_list)) }}"
...
