---
- name: Ensure information about aws placement groups is gathered
  tags:
    - ec2_placement_group_info
  linuxhq.aws.ec2_placement_group_info:
    filters: "{{ ec2_placement_group_info_filters }}"
    group_ids: "{{ ec2_placement_group_info_group_ids or omit }}"
    names: "{{ ec2_placement_group_info_names or omit }}"
    validate_certs: true
  register: __ec2_placement_group_info_query

- name: Ensure list of aws placement groups is generated
  tags:
    - ec2_placement_group_info
  ansible.builtin.set_fact:
    _ec2_placement_group_info_list:
      "{{ __ec2_placement_group_info_query.placement_groups |
          d([]) }}"

- name: Ensure dict of aws placement groups is generated
  tags:
    - ec2_placement_group_info
  ansible.builtin.set_fact:
    _ec2_placement_group_info_dict:
      "{{ dict(_ec2_placement_group_info_list |
               json_query('[].group_name') |
               zip(_ec2_placement_group_info_list)) }}"
...
