---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - cloudwatchlogs_log_group_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _cloudwatchlogs_log_group_info_dict['molecule-00'].arn is defined
          - _cloudwatchlogs_log_group_info_dict['molecule-00'].log_group_name is defined
          - _cloudwatchlogs_log_group_info_dict['molecule-00'].retention_in_days == 30
          - _cloudwatchlogs_log_group_info_dict['molecule-01'].arn is defined
          - _cloudwatchlogs_log_group_info_dict['molecule-01'].log_group_name is defined
          - _cloudwatchlogs_log_group_info_dict['molecule-01'].retention_in_days == 60
          - _cloudwatchlogs_log_group_info_dict['molecule-02'].arn is defined
          - _cloudwatchlogs_log_group_info_dict['molecule-02'].log_group_name is defined
          - _cloudwatchlogs_log_group_info_dict['molecule-02'].retention_in_days == 120

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        cloudwatchlogs_log_group_list:
          "{{ cloudwatchlogs_log_group_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _verify }}"
      loop:
        - cloudwatchlogs_log_group
      loop_control:
        label: "{{ _verify }}"
        loop_var: _verify
...
