---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: wafv2_ip_set
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - wafv2_ip_set_info
...
