---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - wafv2_ip_set_info

  post_tasks:
    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _wafv2_ip_set_info_dict['molecule-cloudflare'].arn is defined
          - _wafv2_ip_set_info_dict['molecule-cloudflare'].addresses | length == 1
          - _wafv2_ip_set_info_dict['molecule-cloudflare'].ip_address_version == 'IPV4'
          - _wafv2_ip_set_info_dict['molecule-cloudflare'].id is defined
          - _wafv2_ip_set_info_dict['molecule-google'].arn is defined
          - _wafv2_ip_set_info_dict['molecule-google'].addresses | length == 2
          - _wafv2_ip_set_info_dict['molecule-google'].ip_address_version == 'IPV4'
          - _wafv2_ip_set_info_dict['molecule-google'].id is defined

    - name: Ensure ip set id filter target is generated
      ansible.builtin.set_fact:
        wafv2_ip_set_info_id_filter:
          "{{ _wafv2_ip_set_info_dict['molecule-cloudflare'].id }}"

    - name: Ensure info role supports ip set id filters
      ansible.builtin.include_role:
        name: wafv2_ip_set_info
      vars:
        wafv2_ip_set_info_id: "{{ wafv2_ip_set_info_id_filter }}"

    - name: Ensure ip set id filter is verified
      ansible.builtin.assert:
        that:
          - _wafv2_ip_set_info_list | length == 1
          - _wafv2_ip_set_info_dict['molecule-cloudflare'].id == wafv2_ip_set_info_id_filter

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        wafv2_ip_set_list:
          "{{ wafv2_ip_set_list |
              map('combine',
                  {'addresses': [], 'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _verify }}"
      loop:
        - wafv2_ip_set
      loop_control:
        label: "{{ _verify }}"
        loop_var: _verify
...
