---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  tasks:
    - name: Ensure role is included without filters
      ansible.builtin.include_role:
        name: iam_oidc_provider_info

    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _iam_oidc_provider_info_dict['oidc.molecule.example.com'].client_id_list.0 == 'sts.amazonaws.com'
          - _iam_oidc_provider_info_dict['oidc.molecule.example.com'].tags.Name == 'molecule-oidc-provider'

    - name: Ensure oidc provider arn filter target is generated
      ansible.builtin.set_fact:
        iam_oidc_provider_info_arn_filter:
          "{{ _iam_oidc_provider_info_dict['oidc.molecule.example.com'].open_id_connect_provider_arn }}"

    - name: Ensure role is included with arn
      ansible.builtin.include_role:
        name: iam_oidc_provider_info
      vars:
        iam_oidc_provider_info_arn: "{{ iam_oidc_provider_info_arn_filter }}"

    - name: Ensure info with arn is verified
      ansible.builtin.assert:
        that:
          - _iam_oidc_provider_info_list | length == 1
          - _iam_oidc_provider_info_dict['oidc.molecule.example.com'].open_id_connect_provider_arn ==
              iam_oidc_provider_info_arn_filter

    - name: Ensure role is included with url
      ansible.builtin.include_role:
        name: iam_oidc_provider_info
      vars:
        iam_oidc_provider_info_url: "{{ iam_oidc_provider_list.0.url }}"

    - name: Ensure info with url is verified
      ansible.builtin.assert:
        that:
          - _iam_oidc_provider_info_list | length == 1
          - _iam_oidc_provider_info_dict['oidc.molecule.example.com'].client_id_list.0 == 'sts.amazonaws.com'

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        iam_oidc_provider_list:
          "{{ iam_oidc_provider_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _verify }}"
      loop:
        - iam_oidc_provider
      loop_control:
        label: "{{ _verify }}"
        loop_var: _verify
...
