---
- name: Ensure information about aws notifications contacts is gathered
  tags:
    - notifications_contacts_info
  linuxhq.aws.notifications_contacts_info:
    name: "{{ notifications_contacts_info_name or omit }}"
    validate_certs: true
  register: __notifications_contacts_info_query

- name: Ensure list of aws notifications contacts is generated
  tags:
    - notifications_contacts_info
  ansible.builtin.set_fact:
    _notifications_contacts_info_list:
      "{{ __notifications_contacts_info_query.email_contacts |
          d([]) |
          selectattr('address', 'defined') }}"

- name: Ensure dict of aws notifications contacts is generated
  tags:
    - notifications_contacts_info
  ansible.builtin.set_fact:
    _notifications_contacts_info_dict:
      "{{ dict(_notifications_contacts_info_list |
               json_query('[].address') |
               zip(_notifications_contacts_info_list)) }}"
...
