---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - ssm_association_info

    - role: ssm_association
      tags:
        - molecule-idempotence-notest
      check_mode: false

    - ssm_association_info
...
