---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  tasks:
    - name: Ensure role is included without filters
      ansible.builtin.include_role:
        name: ssm_association_info

    - name: Ensure info is verified
      ansible.builtin.assert:
        that:
          - _ssm_association_info_dict['AWS-UpdateSSMAgent'].association_id is defined
          - _ssm_association_info_dict['AWS-UpdateSSMAgent'].name ==
              ssm_association_list.0.name
          - _ssm_association_info_dict['AWS-UpdateSSMAgent'].schedule_expression ==
              ssm_association_list.0.schedule_expression
          - _ssm_association_info_dict['AWS-UpdateSSMAgent'].tags.molecule ==
              'ssm_association_info'
          - _ssm_association_info_dict['AWS-UpdateSSMAgent'].targets ==
              ssm_association_list.0.targets

    - name: Ensure role is included with filters
      ansible.builtin.include_role:
        name: ssm_association_info
      vars:
        ssm_association_info_filters:
          Name: AWS-UpdateSSMAgent

    - name: Ensure info with filters is verified
      ansible.builtin.assert:
        that:
          - _ssm_association_info_dict['AWS-UpdateSSMAgent'].association_id is defined
          - _ssm_association_info_dict['AWS-UpdateSSMAgent'].name ==
              ssm_association_list.0.name

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        ssm_association_list:
          "{{ ssm_association_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _verify }}"
      loop:
        - ssm_association
      loop_control:
        label: "{{ _verify }}"
        loop_var: _verify
...
