---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: ssm_document
      ssm_document_list: []
      tags:
        - molecule-idempotence-notest

    - ssm_document
...
