---
- name: Ensure aws route53 delegation sets are batched
  tags:
    - route53_delegation_set
  ansible.builtin.include_tasks:
    apply:
      tags:
        - route53_delegation_set
    file: include.yml
  loop:
    "{{ route53_delegation_set_list |
        batch(route53_delegation_set_batch) }}"
  loop_control:
    label: "{{ __route53_delegation_set_list | length }}"
    loop_var: __route53_delegation_set_list
...
