---
- name: Ensure aws route53 delegation set defaults are generated
  tags:
    - route53_delegation_set
  ansible.builtin.set_fact:
    __route53_delegation_set_list:
      "{{ [{'state': 'present'}] |
          product(route53_delegation_set_list) |
          map('combine') |
          list }}"

- name: Ensure aws route53 delegation sets are gathered
  tags:
    - route53_delegation_set
  ansible.builtin.command:
    cmd: >
      aws route53 list-reusable-delegation-sets
        --query DelegationSets
  register: __route53_delegation_set_query
  changed_when: false
  check_mode: false

- name: Ensure dict of aws route53 delegation sets is generated
  tags:
    - route53_delegation_set
  ansible.builtin.set_fact:
    __route53_delegation_set_dict:
      "{{ (__route53_delegation_set_query.stdout |
          from_json) |
          list |
          json_query('[].{
            key: CallerReference
            value: Id
          }') |
          items2dict }}"

- name: Ensure aws route53 delegation sets are present
  tags:
    - route53_delegation_set
  ansible.builtin.command:
    cmd: >
      aws route53 create-reusable-delegation-set
        --caller-reference "{{ _delegationset.name }}"
  loop: "{{ __route53_delegation_set_list }}"
  loop_control:
    label: "{{ _delegationset.name | d(none) }}"
    loop_var: _delegationset
  when:
    - _delegationset.name is defined
    - _delegationset.name not in __route53_delegation_set_dict.keys()
    - _delegationset.state == 'present'
  changed_when: true

- name: Ensure aws route53 delegation sets are absent
  tags:
    - route53_delegation_set
  ansible.builtin.command:
    cmd: >
      aws route53 delete-reusable-delegation-set
        --id "{{ __route53_delegation_set_dict[_delegationset.name] }}"
  loop: "{{ __route53_delegation_set_list }}"
  loop_control:
    label: "{{ _delegationset.name | d(none) }}"
    loop_var: _delegationset
  when:
    - _delegationset.name is defined
    - _delegationset.name in __route53_delegation_set_dict.keys()
    - _delegationset.state == 'absent'
  changed_when: true
...
