---
dependencies: []
galaxy_info:
  role_name: ses_identity
  author: Taylor Kimball
  description: Manage aws simple email service identities
  license: GPL-3.0-or-later
  min_ansible_version: 2.18.0
  namespace: linuxhq
  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: macOS
      versions:
        - all
  galaxy_tags:
    - amazon
    - aws
    - email
    - identity
    - service
    - simple
...
