---
- name: Ensure aws route53 records are batched
  tags:
    - route53_record
  ansible.builtin.include_tasks:
    apply:
      tags:
        - route53_record
    file: include.yml
  loop:
    "{{ route53_record_list |
        batch(route53_record_batch) }}"
  loop_control:
    label: "{{ __route53_record_list | length }}"
    loop_var: __route53_record_list
...
