---
- name: Ensure information about aws elastic container registry repositories is gathered
  tags:
    - ecs_ecr_info
  linuxhq.aws.ecs_ecr_info:
    name: "{{ ecs_ecr_info_name or omit }}"
    validate_certs: true
  register: __ecs_ecr_info_query

- name: Ensure list of aws elastic container registry repositories is generated
  tags:
    - ecs_ecr_info
  ansible.builtin.set_fact:
    _ecs_ecr_info_list:
      "{{ __ecs_ecr_info_query.repositories |
          d([]) |
          selectattr('repository_name', 'defined') }}"

- name: Ensure dict of aws elastic container registry repositories is generated
  tags:
    - ecs_ecr_info
  ansible.builtin.set_fact:
    _ecs_ecr_info_dict:
      "{{ dict(_ecs_ecr_info_list |
               json_query('[].repository_name') |
               zip(_ecs_ecr_info_list)) }}"
...
