---
- name: Ensure information about aws elastic container registry repositories is gathered
  tags:
    - ecs_ecr_info
  ansible.builtin.command:
    cmd: >
      aws ecr describe-repositories
        --query repositories
  register: __ecs_ecr_info_query
  changed_when: false
  check_mode: false

- name: Ensure list of aws elastic container registry repositories is generated
  tags:
    - ecs_ecr_info
  ansible.builtin.set_fact:
    _ecs_ecr_info_list:
      "{{ (__ecs_ecr_info_query.stdout |
          from_json) |
          selectattr('repositoryName', 'defined') |
          d([]) }}"

- name: Ensure dict of aws elastic container registry repositories is generated
  tags:
    - ecs_ecr_info
  ansible.builtin.set_fact:
    _ecs_ecr_info_dict:
      "{{ dict(_ecs_ecr_info_list |
               json_query('[].repositoryName') |
               zip(_ecs_ecr_info_list)) }}"
...
