---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9.6
    cpus: 4
    memory: 4096

provisioner:
  name: ansible
  env:
    ANSIBLE_ACTION_WARNINGS: false
    ANSIBLE_DEPRECATION_WARNINGS: false
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /opt/awscli/bin/python
        ec2_vpc_net_list:
          - name: molecule
            cidr_block: 192.168.0.0/24

        ec2_vpc_subnet_list:
          - vpc_id: "{{ _ec2_vpc_net_info_dict['molecule'].id }}"
            subnets:
              - name: molecule-a
                az:
                  "{{ lookup('ansible.builtin.ini',
                             'region',
                             file='~/.aws/config',
                             section='profile molecule') ~ 'a' }}"
                cidr: "{{ ec2_vpc_net_list.0.cidr_block | ansible.utils.ipsubnet(25,0) }}"
              - name: molecule-b
                az:
                  "{{ lookup('ansible.builtin.ini',
                             'region',
                             file='~/.aws/config',
                             section='profile molecule') ~ 'b' }}"
                cidr: "{{ ec2_vpc_net_list.0.cidr_block | ansible.utils.ipsubnet(25,1) }}"

        ec2_security_group_list:
          - vpc_id: "{{ _ec2_vpc_net_info_dict['molecule'].id }}"
            security_groups:
              - name: molecule-route53resolver
                rules:
                  - cidr_ip: 0.0.0.0/0
                    ports:
                      - 53
                      - 443
                    proto: tcp
                  - cidr_ip: 0.0.0.0/0
                    ports:
                      - 53
                    proto: udp
                rules_egress:
                  - cidr_ip: 0.0.0.0/0
                    proto: -1

        route53_resolver_list:
          - name: molecule-cloudflare
            direction: outbound
            ip_addresses:
              - subnet_id: "{{ _ec2_vpc_subnet_info_dict[ec2_vpc_subnet_list.0.subnets.0.name].id }}"
                ip: 192.168.0.125
              - subnet_id: "{{ _ec2_vpc_subnet_info_dict[ec2_vpc_subnet_list.0.subnets.1.name].id }}"
                ip: 192.168.0.253
            security_group_ids:
              - "{{ _ec2_security_group_info_dict['molecule-route53resolver'].group_id }}"

          - name: molecule-google
            direction: outbound
            ip_addresses:
              - subnet_id: "{{ _ec2_vpc_subnet_info_dict[ec2_vpc_subnet_list.0.subnets.0.name].id }}"
                ip: 192.168.0.126
              - subnet_id: "{{ _ec2_vpc_subnet_info_dict[ec2_vpc_subnet_list.0.subnets.1.name].id }}"
                ip: 192.168.0.254
            security_group_ids:
              - "{{ _ec2_security_group_info_dict['molecule-route53resolver'].group_id }}"

        route53_resolver_rule_list_create:
          - name: molecule-cloudflare
            domain_name: cloudflare.com
            resolver_endpoint_id: "{{ _route53_resolver_info_dict['molecule-cloudflare'].id }}"
            rule_type: forward
            target_ips:
              - ip: 1.1.1.1
                port: 53
              - ip: 1.1.1.2
                port: 53

          - name: molecule-google
            domain_name: google.com
            resolver_endpoint_id: "{{ _route53_resolver_info_dict['molecule-google'].id }}"
            rule_type: forward
            target_ips:
              - ip: 8.8.8.8
                port: 53
              - ip: 8.8.8.4
                port: 53

        route53_resolver_rule_list_update:
          - name: molecule-cloudflare
            domain_name: cloudflare.com
            resolver_endpoint_id: "{{ _route53_resolver_info_dict['molecule-cloudflare'].id }}"
            rule_type: forward
            target_ips:
              - ip: 1.1.1.3
                port: 53
              - ip: 1.1.1.4
                port: 53

          - name: molecule-google
            domain_name: google.com
            resolver_endpoint_id: "{{ _route53_resolver_info_dict['molecule-google'].id }}"
            rule_type: forward
            target_ips:
              - ip: 8.8.8.9
                port: 53
              - ip: 8.8.8.5
                port: 53

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
