---
- name: Ensure aws route53 zones are batched
  tags:
    - route53_zone
  ansible.builtin.include_tasks:
    apply:
      tags:
        - route53_zone
    file: include.yml
  loop:
    "{{ route53_zone_list |
        batch(route53_zone_batch) }}"
  loop_control:
    label: "{{ __route53_zone_list | length }}"
    loop_var: __route53_zone_list
...
