---
- name: Ensure aws notifications hub default is present
  tags:
    - notifications_hub
  linuxhq.aws.notifications_hub:
    region: us-east-1
    validate_certs: true

- name: Ensure aws notifications hubs are batched
  tags:
    - notifications_hub
  ansible.builtin.include_tasks:
    apply:
      tags:
        - notifications_hub
    file: include.yml
  loop:
    "{{ notifications_hub_list |
        batch(notifications_hub_batch) }}"
  loop_control:
    label: "{{ __notifications_hub_list | length }}"
    loop_var: __notifications_hub_list
...
