---
- name: Ensure aws simple storage service bucket lifecycle rules are batched
  tags:
    - s3_lifecycle
  ansible.builtin.include_tasks:
    apply:
      tags:
        - s3_lifecycle
    file: include.yml
  loop:
    "{{ q('ansible.builtin.subelements',
          s3_lifecycle_list,
          'lifecycle_rules',
          {'skip_missing': true}) |
        batch(s3_lifecycle_batch) }}"
  loop_control:
    label: "{{ __s3_lifecycle_list | length }}"
    loop_var: __s3_lifecycle_list
...
