---
- name: Converge
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - role: wafv2_ip_set
      wafv2_ip_set_list: []
      tags:
        - molecule-idempotence-notest

    - role: wafv2_ip_set
      tags:
        - molecule-idempotence-notest

    - role: wafv2_ip_set
      wafv2_ip_set_list: "{{ wafv2_ip_set_updated_list }}"
...
