---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: vagrant

platforms:
  - name: almalinux9
    box: bento/almalinux-9.6
    cpus: 4
    memory: 4096

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /opt/awscli/bin/python
        wafv2_ip_set_list:
          - name: molecule-cloudflare
            addresses:
              - 1.1.1.1/32
            ip_address_version: ipv4
            scope: regional

          - name: molecule-google
            addresses:
              - 8.8.8.8/32
              - 8.8.8.4/32
            ip_address_version: ipv4
            scope: regional

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
