---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  pre_tasks:
    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        wafv2_ip_set_list:
          "{{ wafv2_ip_set_list |
              map('combine',
                  {'addresses': [],
                   'state': 'absent'}) }}"

  roles:
    - wafv2_ip_set
...
