---
- name: Ensure information about aws simple queue service availability zones is gathered
  tags:
    - sqs_queue
  amazon.aws.aws_az_info:
    validate_certs: true
  register: __sqs_queue_info_availability_zone

- name: Ensure string of aws simple queue service region is generated
  tags:
    - sqs_queue
  ansible.builtin.set_fact:
    __sqs_queue_info_region:
      "{{ __sqs_queue_info_availability_zone.availability_zones.0.region_name }}"

- name: Ensure information about aws simple queue service queues is gathered
  tags:
    - sqs_queue
  linuxhq.aws.sqs_queue_info:
    name: "{{ sqs_queue_info_name or omit }}"
    queue_name_prefix: "{{ sqs_queue_info_queue_name_prefix or omit }}"
    queue_owner_aws_account_id:
      "{{ sqs_queue_info_queue_owner_aws_account_id or omit }}"
    region: "{{ __sqs_queue_info_region }}"
    validate_certs: true
  register: __sqs_queue_info_query

- name: Ensure list of aws simple queue service queues is generated
  tags:
    - sqs_queue
  ansible.builtin.set_fact:
    _sqs_queue_info_list:
      "{{ __sqs_queue_info_query.queues |
          d([]) |
          list }}"

- name: Ensure dict of aws simple queue service queues is generated
  tags:
    - sqs_queue_info
  ansible.builtin.set_fact:
    _sqs_queue_info_dict:
      "{{ dict(_sqs_queue_info_list |
               json_query('[].name') |
               zip(_sqs_queue_info_list)) }}"
...
