---
- name: Ensure information about aws wafv2 ip sets is gathered
  tags:
    - wafv2_ip_set_info
  ansible.builtin.command:
    cmd: >
      aws wafv2 list-ip-sets
        --query IPSets
        --scope "{{ wafv2_ip_set_info_scope | upper }}"
  register: __wafv2_ip_set_info_query
  changed_when: false
  check_mode: false

- name: Ensure list of aws wafv2 ip set ids is generated
  tags:
    - wafv2_ip_set_info
  ansible.builtin.set_fact:
    __wafv2_ip_set_info_ids:
      "{{ (__wafv2_ip_set_info_query.stdout |
          from_json) |
          selectattr('Name', 'defined') |
          d([]) }}"

- name: Ensure information about aws wafv2 ip sets is gathered
  tags:
    - wafv2_ip_set_info
  ansible.builtin.command:
    cmd: >
      aws wafv2 get-ip-set
        --id "{{ _ipset.Id }}"
        --name "{{ _ipset.Name }}"
        --query IPSet
        --scope "{{ wafv2_ip_set_info_scope | upper }}"
  register: __wafv2_ip_set_info_list
  loop: "{{ __wafv2_ip_set_info_ids }}"
  loop_control:
    label: "{{ _ipset.Name | d(none) }}"
    loop_var: _ipset
  when:
    - _ipset.Id is defined
    - _ipset.Name is defined
  changed_when: false
  check_mode: false

- name: Ensure list of aws wafv2 ip sets is generated
  tags:
    - wafv2_ip_set_info
  ansible.builtin.set_fact:
    _wafv2_ip_set_info_list:
      "{{ __wafv2_ip_set_info_list.results |
          map(attribute='stdout') |
          map('from_json') }}"

- name: Ensure dict of aws wafv2 ip sets is generated
  tags:
    - wafv2_ip_set_info
  ansible.builtin.set_fact:
    _wafv2_ip_set_info_dict:
      "{{ dict(_wafv2_ip_set_info_list |
               json_query('[].Name') |
               zip(_wafv2_ip_set_info_list)) }}"
...
