---
- name: Ensure information about aws wafv2 ip sets is gathered
  tags:
    - wafv2_ip_set_info
  linuxhq.aws.wafv2_ip_set_info:
    id: "{{ wafv2_ip_set_info_id or omit }}"
    name: "{{ wafv2_ip_set_info_name or omit }}"
    scope: "{{ wafv2_ip_set_info_scope }}"
    validate_certs: true
  register: __wafv2_ip_set_info_query

- name: Ensure list of aws wafv2 ip sets is generated
  tags:
    - wafv2_ip_set_info
  ansible.builtin.set_fact:
    _wafv2_ip_set_info_list:
      "{{ __wafv2_ip_set_info_query.ip_sets |
          d([]) }}"

- name: Ensure dict of aws wafv2 ip sets is generated
  tags:
    - wafv2_ip_set_info
  ansible.builtin.set_fact:
    _wafv2_ip_set_info_dict:
      "{{ dict(_wafv2_ip_set_info_list |
               json_query('[].name') |
               zip(_wafv2_ip_set_info_list)) }}"
...
