---
- name: Ensure information about aws simple email service account details is gathered
  tags:
    - ses_sandbox_info
  linuxhq.aws.ses_sandbox_info:
    validate_certs: true
  register: __ses_sandbox_info_query

- name: Ensure dict of aws simple email service account details is generated
  tags:
    - ses_sandbox_info
  ansible.builtin.set_fact:
    _ses_sandbox_info_dict:
      "{{ __ses_sandbox_info_query.account | d({}) }}"
...
