---
- name: Ensure aws wafv2 web acl log group is absent
  tags:
    - wafv2_web_acl
  amazon.aws.cloudwatchlogs_log_group:
    log_group_name: "aws-waf-logs-{{ _webacl.name }}"
    state: absent

- name: Ensure aws wafv2 web acl is absent
  tags:
    - wafv2_web_acl
  community.aws.wafv2_web_acl:
    name: "{{ _webacl.name }}"
    scope: "{{ _webacl.scope | upper }}"
    state: absent
...
