---
- name: Ensure aws wafv2 web acls are present
  tags:
    - wafv2_web_acl
  community.aws.wafv2_web_acl:
    cloudwatch_metrics: "{{ _webacl.cloudwatch_metrics | d(true) }}"
    custom_response_bodies: "{{ _webacl.custom_response_bodies | d(omit) }}"
    default_action: "{{ _webacl.default_action }}"
    description: "{{ _webacl.description | d(_webacl.name) }}"
    metric_name: "{{ _webacl.metric_name | d(omit) }}"
    name: "{{ _webacl.name }}"
    purge_rules: "{{ _webacl.purge_rules | d(true) }}"
    purge_tags: "{{ _webacl.purge_tags | d(true) }}"
    rules: "{{ _webacl.rules }}"
    sampled_requests: "{{ _webacl.sampled_requests | d(false) }}"
    scope: "{{ _webacl.scope | upper }}"
    state: present
    tags:
      "{{ _webacl.tags |
          d({}) |
          combine({'Name': _webacl.name}) }}"
    validate_certs: true
  register: __wafv2_web_acl_result
  loop: "{{ __wafv2_web_acl_list }}"
  loop_control:
    label: "{{ _webacl.name | d(none) }}"
    loop_var: _webacl
  async: "{{ ansible_check_mode | ternary(0, wafv2_web_acl_async) }}"
  poll: "{{ wafv2_web_acl_poll }}"
  when:
    - _webacl.default_action is defined
    - _webacl.name is defined
    - _webacl.rules is defined
    - _webacl.rules | length > 0
    - _webacl.scope is defined
    - _webacl.state == 'present'
  changed_when:
    - ansible_check_mode | bool
    - __wafv2_web_acl_result.changed | bool

- name: Ensure present aws wafv2 web acl jobs are complete
  tags:
    - wafv2_web_acl
  ansible.builtin.async_status:
    jid: "{{ _jid.ansible_job_id }}"
  register: __wafv2_web_acl_status
  loop: "{{ __wafv2_web_acl_result.results }}"
  loop_control:
    label: "{{ _jid._webacl.name | d(none) }}"
    loop_var: _jid
  when:
    - _jid.ansible_job_id is defined
  until:
    - __wafv2_web_acl_status.finished | bool
  retries: "{{ wafv2_web_acl_retries }}"
  delay: "{{ wafv2_web_acl_delay }}"

- name: Ensure aws wafv2 web acls are absent
  tags:
    - wafv2_web_acl
  community.aws.wafv2_web_acl:
    name: "{{ _webacl.name }}"
    scope: "{{ _webacl.scope | upper }}"
    state: absent
    validate_certs: true
  register: __wafv2_web_acl_result
  loop: "{{ __wafv2_web_acl_list }}"
  loop_control:
    label: "{{ _webacl.name | d(none) }}"
    loop_var: _webacl
  async: "{{ ansible_check_mode | ternary(0, wafv2_web_acl_async) }}"
  poll: "{{ wafv2_web_acl_poll }}"
  when:
    - _webacl.name is defined
    - _webacl.scope is defined
    - _webacl.state == 'absent'
  changed_when:
    - ansible_check_mode | bool
    - __wafv2_web_acl_result.changed | bool

- name: Ensure absent aws wafv2 web acl jobs are complete
  tags:
    - wafv2_web_acl
  ansible.builtin.async_status:
    jid: "{{ _jid.ansible_job_id }}"
  register: __wafv2_web_acl_status
  loop: "{{ __wafv2_web_acl_result.results }}"
  loop_control:
    label: "{{ _jid._webacl.name | d(none) }}"
    loop_var: _jid
  when:
    - _jid.ansible_job_id is defined
  until:
    - __wafv2_web_acl_status.finished | bool
  retries: "{{ wafv2_web_acl_retries }}"
  delay: "{{ wafv2_web_acl_delay }}"
...
