---
- name: Converge
  hosts: all
  roles:
    - role: rds_instance_param_group
      rds_instance_param_group_list: []
      tags:
        - molecule-idempotence-notest

    - rds_instance_param_group
...
