---
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml

driver:
  name: default
  options:
    managed: false
    ansible_connection_options:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"

platforms:
  - name: localhost

provisioner:
  name: ansible
  env:
    ANSIBLE_ACTION_WARNINGS: false
    ANSIBLE_DEPRECATION_WARNINGS: false
  log: true
  options:
    diff: true
  inventory:
    group_vars:
      all:
        sqs_queue_list:
          - name: molecule-info-bounce
            policy:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    AWS:
                      - "arn:aws:iam::{{ _aws_caller_info_account }}:root"
                  Action:
                    - sqs:*
                  Resource:
                    - "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-info-bounce"
                - Effect: Allow
                  Principal:
                    Service: sns.amazonaws.com
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-info-bounce"
                  Condition:
                    ArnEquals:
                      'aws:SourceArn':
                        "arn:aws:sns:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-info-bounce"

          - name: molecule-info-complaint
            policy:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    AWS:
                      - "arn:aws:iam::{{ _aws_caller_info_account }}:root"
                  Action:
                    - sqs:*
                  Resource:
                    - "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-info-complaint"
                - Effect: Allow
                  Principal:
                    Service: sns.amazonaws.com
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-info-complaint"
                  Condition:
                    ArnEquals:
                      'aws:SourceArn':
                        "arn:aws:sns:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-info-complaint"

          - name: molecule-info-delivery
            policy:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Principal:
                    AWS:
                      - "arn:aws:iam::{{ _aws_caller_info_account }}:root"
                  Action:
                    - sqs:*
                  Resource:
                    - "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-info-delivery"
                - Effect: Allow
                  Principal:
                    Service: sns.amazonaws.com
                  Action:
                    - sqs:SendMessage
                  Resource:
                    - "arn:aws:sqs:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-info-delivery"
                  Condition:
                    ArnEquals:
                      'aws:SourceArn':
                        "arn:aws:sns:{{ _aws_az_info_list_l.0[:-1] }}:{{ _aws_caller_info_account }}:molecule-info-delivery"

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - check
    - idempotence
    - verify
    - cleanup
    - destroy

verifier:
  name: ansible
  options:
    diff: true
...
