---
- name: Verify
  hosts: all
  environment:
    PATH: '/opt/awscli/bin'

  roles:
    - aws_az_info
    - aws_caller_info

  post_tasks:
    - name: Ensure role is included without name
      ansible.builtin.include_role:
        name: sqs_queue_info
      vars:
        sqs_queue_info_name: null

    - name: Ensure info without name is verified
      ansible.builtin.assert:
        that:
          - _sqs_queue_info_dict['molecule-bounce'].queue_arn is defined
          - _sqs_queue_info_dict['molecule-bounce'].sqs_managed_sse_enabled | bool
          - _sqs_queue_info_dict['molecule-complaint'].queue_arn is defined
          - _sqs_queue_info_dict['molecule-complaint'].sqs_managed_sse_enabled | bool
          - _sqs_queue_info_dict['molecule-delivery'].queue_arn is defined
          - _sqs_queue_info_dict['molecule-delivery'].sqs_managed_sse_enabled | bool

    - name: Ensure role is included with name
      ansible.builtin.include_role:
        name: sqs_queue_info
      vars:
        sqs_queue_info_name: molecule-bounce

    - name: Ensure info with name is verified
      ansible.builtin.assert:
        that:
          - _sqs_queue_info_list | length == 1
          - _sqs_queue_info_list.0.name == 'molecule-bounce'
          - _sqs_queue_info_dict.keys() | list == ['molecule-bounce']
          - _sqs_queue_info_dict['molecule-bounce'].queue_arn is defined
          - _sqs_queue_info_dict['molecule-bounce'].sqs_managed_sse_enabled | bool

    - name: Ensure role is included with queue name prefix
      ansible.builtin.include_role:
        name: sqs_queue_info
      vars:
        sqs_queue_info_queue_name_prefix: molecule-

    - name: Ensure info with queue name prefix is verified
      ansible.builtin.assert:
        that:
          - _sqs_queue_info_list | length == 3
          - _sqs_queue_info_dict.keys() | sort ==
              ['molecule-bounce', 'molecule-complaint', 'molecule-delivery']

    - name: Ensure inventory lists are formatted
      ansible.builtin.set_fact:
        sqs_queue_list:
          "{{ sqs_queue_list |
              map('combine', {'state': 'absent'}) }}"

    - name: Ensure roles are included
      ansible.builtin.include_role:
        name: "{{ _verify }}"
      loop:
        - sqs_queue
      loop_control:
        label: "{{ _verify }}"
        loop_var: _verify
...
